### ISSUE TITLE
Duplicate Column Name: callback_xxx

### ISSUE THREAD

**Issue by carlituxman** [MedicOneSystems/livewire-datatables#101]
If I use more than once the same: 
`Column::callback(['id'], function( $id) {...`

can be possible assign name like ->name('nameiwant')

**Comment by xrezut** [comment]
Are you looking to label a column? If so you can do `Column::callback(....)->('name_you_want')`

**Comment by carlituxman** [comment]
Not, I mean give a name to the callback function, internally do callback_xxxx where xxx is a json of the parameters, if we create two callback columns with same parameters crash because callback_xxxx is in use.

**Comment by ousid** [comment]
You call a callback with `id` column because it's already reserved, try chose another column.

**Comment by carlituxman** [comment]
Well. But not with id only, this happens with (['id', 'status']), or more parameters

**Comment by ousid** [comment]
Can you share your `datatableModel` Code?

**Comment by carlituxman** [comment]
See this for example:
`
public function columns()
{
        return [
            Column::name('name'),
            Column::callback(['id','status'], function ($id, $status) {
                //
            }),
            Column::callback(['id','status'], function ($id, $status) {
                //
            }),
        ];
}
`

**Comment by ousid** [comment]
Why you are returning `id` and `status` in the same time?

And yes, the ID is reserved as I said to you before.

**Comment by carlituxman** [comment]
This an example. Can be another use of parameters. I only propose can name callbacks.

**Comment by ousid** [comment]
> This an example. Can be another use of parameters. I only propose can name callbacks.

I notice that just days ago TBH, but you can even call two column (e.g: id, name) and use just the id, you are not forced to use them both except passing them to the callback function.
EX:
```php
Column::callback(['id', 'name'], function ($id, $name) {
   return $id;
});
```

**Comment by amaurycid** [comment]
A temporary solution for me was to change parameter order (in first callback: ['id', 'status'], in second: ['status', 'id']).

**Comment by JaviFern** [comment]
Hi, I posted a posible solution in #109 , I suppose this is the right place for it. Is a (very) simple version of callback function that allows several callbacks from the same field, copy here:

...but, what about if you need several callbacks from a field? this can be a solution (please comment if you see some can be done in a better way)...

Scenario
we have a table that requires more than 1 callback from a single field:

 ```
                Column::callback('field', function ($value) {
                    // do something
                    // return something
                })
                    ->label('label1'),           

                 Column::callback('field', function ($value) {
                    // do something
                    // return something
                })
                    ->label('label2') 
```             

then we get the "duplicate name" error...
If we analyze the callback function, in Column.php:

```
public static function callback($columns, $callback, $params = [])
   {
       $column = new static;

       $column->name = 'callback_'.crc32(json_encode(func_get_args()));
       $column->callback = $callback;
       $column->additionalSelects = is_array($columns) ? $columns : array_map('trim', explode(',', $columns));
       $column->params = $params;

       return $column;
   }
```
we can see as the field name is used to encode the name of the callback, then, we use it twice in the sql query... it won't work.

the next solution works: I define a new function in Column.php (I know is a bad practice modify vendor files, then I have a copy in my app folder and modified composer.json to look this file), I name the function (imagine) callback2 and added it just below the old callback:

```
public static function callback2($name_aux, $columns, $callback, $params = [])
    {
        $column = new static;

        $column->name = 'callback_'.crc32(json_encode(func_get_args()).$name_aux);
        $column->callback = $callback;
        $column->additionalSelects = is_array($columns) ? $columns : array_map('trim', explode(',', $columns));
        $column->params = $params;

        return $column;
    }
```
now we add an aux string to make differents callback names, then we can do the first like:

```
                Column::callback2('aux1', 'field', function ($value) {
                    // do something
                    // return something
                })
                    ->label('label1'),           

                 Column::callback2('aux2', 'field', function ($value) {
                    // do something
                    // return something
                })
                    ->label('label2')  
```
I'm not an expert (this is my first post) and I dont'know if I'm doing some disaster, I hope the idea helps

**Comment by Renaud404** [comment]
@JaviFern just make a pull request if you have a good solution ?

**Comment by marksalmon** [comment]
No PR required!

Just pass a unique name as the third argument to the callback method:

```php
Column::callback(['id', 'name'], function ($id, $name) {
   return $id;
}, 'anyoldshit');
```

**Comment by xTiiX** [comment]
@marksalmon Do i really need to use the vendor modification option or is it just a new update breaker ?

![2021-11-25 10_22_25-Window](https://user-images.githubusercontent.com/56162267/143414536-a412a574-14e3-4d30-af42-a39b8fb84ed9.png)
![2021-11-25 10_21_58-Window](https://user-images.githubusercontent.com/56162267/143414540-de54684f-b9bb-43f7-9549-b6d2ce89b78e.png)

**Comment by xTiiX** [comment]
Sorry, just got a wrong sql search -_-
PS : Fantastic package !
