### ISSUE TITLE
MS SQL query error

### ISSUE THREAD

**Issue by goldjunge4** [MedicOneSystems/livewire-datatables#104]
Hello,

I need to say that the package is really great but I am now stuck with an issue where I don't find any solution.

I have implemented everything according to the GitHub repo and the example files but every time I sort my table the query is wrong and the SQL Server throws an error because the sort field is wrapped into ''.
I have copied the query from the data table and tried it in my SQL studio and the same issue. If I delete the '' in the query it is working fine. Change I config this somewhere?

Wrong generated query: `select top 10 [stops].[start] as [start] from [stops] order by 'start' desc`
correct one: `select top 10 [stops].[start] as [start] from [stops] order by start desc`

**Comment by tamazao** [comment]
I am having the same issue.  Would be great to be able to use this.

**Comment by michiel-van-den-anker** [comment]
I had the same issue so I patched in my fork: https://github.com/michiel-van-den-anker/livewire-datatables
