### ISSUE TITLE
Accessors not working Inside datatable

### ISSUE THREAD

**Issue by ousid** [MedicOneSystems/livewire-datatables#105]
I'm trying to change some columns before showing them inside the `datatable`, but it seems not working inside the table but outside it working very well.

This is what I'm trying to achieve:

```php
    public function getPriceAttribute($value)
    {
        $price = App::getLocale() == 'ar' ? __('DA') . ' ' . $value : $value . ' ' . __('DA');
        return $price;
    }
```

Inside `ProductTable` component:

```php
...
public function columns()
{
     return [
              ....
            NumberColumn::name('price')
                ->label(__('Product Price'))
                ->filterable()
                ->alignCenter(),
            ....
      ];
}
```

### Screenshot
![image](https://user-images.githubusercontent.com/21012933/103101891-ee3c7b80-4619-11eb-8319-1bc47666655c.png)

**Comment by marksalmon** [comment]
Eloquent accessors won't work because this package uses the query builder to generate the DB query, and does not hydrate the models. You can do this manually using a callback column.
