### ISSUE TITLE
Filter data so that only rows where 'column name' = 1 are displayed

### ISSUE THREAD

**Issue by sirhB** [MedicOneSystems/livewire-datatables#106]
Is there a way to prevent a row from showing if specific column within the row has x value?

**Comment by sirhB** [comment]
I have a boolean column called "archived". I only want to display rows where archived = 0

**Comment by alessandroboscato** [comment]
Cannot you simply use in the builder method the ::where instead of ::query? That should work.

**Comment by yassermohammad** [comment]
Yes, you can do as this:
`
public function builder()
    {
        $agent = OrderFaxing::where('order_faxing.agent_id', auth()->user()->id);
        return $agent;
    }
`
OrderFaxing is my model and it has a foreign key called agent_id and I filter the query or request by this way.
