### ISSUE TITLE
how send parameter to component

### ISSUE THREAD

**Issue by mehrdadnateghi** [MedicOneSystems/livewire-datatables#108]
i want to send parameters to component but I receive this error

ErrorException
Declaration of App\Http\Livewire\Tables\OrderItemsBuyerTable::mount($params) should be compatible with Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable::mount($model = NULL, $include = Array, $exclude = Array, $hide = Array, $dates = Array, $times = Array, $searchable = Array, $sort = NULL, $hideHeader = NULL, $hidePagination = NULL, $perPage = 10, $exportable = false, $hideable = false, $beforeTableSlot = false, $afterTableSlot = false, $params = Array) 

i cant use mount method for this

**Comment by sjjbakker** [comment]
@mehrdad-nateghi You can pass parameters by the $params array in the boot method. For example:

```
    public function builder()
    {

        dd($this->params);

    	return Shipment::query()
    	->where('user_id', \Auth::user()->id);

    }
```

`@livewire('tables.example-table', ['params' => 3])`

Which would result in die and dumping the number 3.

**Comment by mehrdad-nateghi** [comment]
I used this way. thanks @sjjbakker

**Comment by nbarshain** [comment]
I've been looking all over for at least an hour about how to do this, and thanks to you I got it!

BTW you can use one of the other predefined parameters too, such as `model`

**Comment by muath-ye** [comment]
I used params 
```<liveware:example-table params="3" />```
and it worked for me but can I pass an array
