### ISSUE TITLE
formatting columns

### ISSUE THREAD

**Issue by Sandman83** [MedicOneSystems/livewire-datatables#114]
Question: How to format (the width of a) single column(s)? 

I mean, I found the ->view functionality. However, with this I'm able to format only the content cells of the table. This is much but not enough: 
In my case, the filtering fields of the id column stretch the column too much beyond the maximum string length. So, I modified the class of the input field in number.blade.php by an if clause to

    class="m-1 pr-6 text-sm leading-4 flex-grow form-input @if($index === 1 && $name === 'Id')w-28 @endif"

How to process in general case?

**Comment by marksalmon** [comment]
Publish the blade views and then you can do whatever you like
