### ISSUE TITLE
Using searchable with a callback

### ISSUE THREAD

**Issue by EricPaulson** [MedicOneSystems/livewire-datatables#115]
It seems I can't make a column searchable using a callback. Is this a known issue?

    Column::callback(["id"], function ($id) {
            return Bill::with("citations")->find($id)->citations->implode("section_reference");
        })
        ->label("Citations")
        ->searchable(),

An example value might be something like 123.456. But when I search for that, it does not show up in the results. Any ideas?

**Comment by EricPaulson** [comment]
For anyone with a similar issue or really anything at all related to search or searchable columns, you can do pretty much anything you want by simply overriding the addGlobalSearch() method in your Livewire class. As long as you extend LivewireDatatable in your class you'll be good. 

Here's an example of what I did:

    public function addGlobalSearch()
    {
        if (! $this->search) {
            return $this;
        }

        $this->query = Bill::smartSearch($this->query, $this->search);

        return $this;
    }

My smartSearch method is just a function on the model that returns an eloquent collection based on my own rules. With this you can have as complex a query for search as you want.

**Comment by Sandman83** [comment]
> It seems I can't make a column searchable using a callback. Is this a known issue?
> 
> ```
> Column::callback(["id"], function ($id) {
>         return Bill::with("citations")->find($id)->citations->implode("section_reference");
>     })
>     ->label("Citations")
>     ->searchable(),
> ```
> 
> An example value might be something like 123.456. But when I search for that, it does not show up in the results. Any ideas?

At least, this is not as generic as you describe. I have 

    Column::callback(['person.last_name', 'person.first_name'], function($last_name, $first_name){
        return $lastName . ' ' . $firstName;
    })->label('Name')
    ->searchable()

and it works, even with proper highlighting.
