### ISSUE TITLE
I Fund This Error When Use Email Field and Search it

### ISSUE THREAD

**Issue by mbd24** [MedicOneSystems/livewire-datatables#117]
ErrorException
Undefined index: slot (View: G:\laragon\www\iqpos\vendor\mediconesystems\livewire-datatables\resources\views\livewire\datatables\datatable.blade.php)

Show Popup this Error when use email field and Editable at a time and Search any fields Fast. But when disable email field or Disable Editable option then no error show. I want enable email and editable at a time but Error and Error.
And How to Style my row column for mobile view ?
Plz Any one tell me any solution . Advance Thank

**Comment by websolutely** [comment]
same issue here

**Comment by MehdiAghighi** [comment]
did you found any solutions ?
