### ISSUE TITLE
The Page parameter in the url changes the page in all tables

### ISSUE THREAD

**Issue by victorelec14** [MedicOneSystems/livewire-datatables#119]
When changing the page in a table the "page" parameter is put in the URL and in case you have 2 or more datatables when you try to reload the web it will change the page in all the datatables to the same page.

> test?page=2

![image](https://user-images.githubusercontent.com/543450/104563873-82fb2d80-564a-11eb-963e-b13ecdea68ff.png)

**Comment by boynet** [comment]
make sense since same parameter is used for both tables..
you will need to change the pagination page name(google it)
and then I you will also need to change some logic inside `WithPagination` trait has the 'page' parameter is hard coded there

**Comment by victorelec14** [comment]
give a way to disable this "page" parameter after change a page? 

Thanks

**Comment by victorelec14** [comment]
Related: https://github.com/livewire/livewire/pull/1997
