### ISSUE TITLE
LinkTo

### ISSUE THREAD

**Issue by ewkilian** [MedicOneSystems/livewire-datatables#124]
Hi,
It's possible to add LinkTo on a Column "Name" (for example) to a ID (for example) ?
When I click on the Name, I go to : URL/example/1
Thank you

**Comment by jamesbhatta** [comment]
```php
 NumberColumn::name('id')
                ->label('ID')
                ->filterable()
                ->linkTo('user', 6),
```

Demo here: https://livewire-datatables.com/complex

**Comment by ewkilian** [comment]
Hi,
Thank you, I see this command on the documentation, but that is OK, on the ID col. your exemple give the result :
.../user/2   (id=2 in my exemple)
But I such a solution to add this Link on a another one col,   for exemple the col "Name" with the ID value (and not the Name value)
Have you a idea ?
Thank you a lot

**Comment by Tedderouni** [comment]
I'm also looking for this functionality.  Were you able to find a solution?

**Comment by ewkilian** [comment]
Sorry I don't find at the moment 😪

**Comment by Tedderouni** [comment]
I realized this could be done with a [callback](https://github.com/MedicOneSystems/livewire-datatables#callbacks).

For example:
```
Column::callback(['name', 'id'], function ($name, $id) {
    return "<a href='" . route('users.show', ['user' => $id]) . "'>$name</a>";
})
->defaultSort('asc')
->label('name'),
```

**Comment by Cigoler** [comment]
> I realized this could be done with a [callback](https://github.com/MedicOneSystems/livewire-datatables#callbacks).
> 
> For example:
> 
> ```
> Column::callback(['name', 'id'], function ($name, $id) {
>     return "<a href='" . route('users.show', ['user' => $id]) . "'>$name</a>";
> })
> ->defaultSort('asc')
> ->label('name'),
> ```

This works great, cheers. 

I think it would be a neat addition to add something like this to the base functionality. Allowing a second argument for what link to use (id, slug etc) is quite a common task I think.
