### ISSUE TITLE
Feature request: choose columns to export 

### ISSUE THREAD

**Issue by Sandman83** [MedicOneSystems/livewire-datatables#126]
Are you able to provide a switch similar to "exclude" like "excludeOnExport" to drop specific columns on excel export? 
In my case, I have a table both with checkboxes and ids. Within the export I get the id column twice. I would like to drop the checkbox column as in this case it does not carry any further information. 
See also #125 , as I managed to do so inside a customized getSelectStatements function.

**Comment by ValulifeAndy** [comment]
You can override the export function from the datatable class you are using,
For example

```
use App\Exports\UsersExport;

public function export(){
        return (new UsersExport)->download('Users.csv');
    }
```
