### ISSUE TITLE
Unable to pass ID to livewire-datatable component via any of livewire::mount methods

### ISSUE THREAD

**Issue by rvigneshw** [MedicOneSystems/livewire-datatables#128]
I've tried this,
@livewire('component', ['id' => $id])

Received this error

Declaration of App\Http\Livewire\DisplayData::mount($id) must be compatible with Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable::mount($model = null, $include = [], $exclude = [], $hide = [], $dates = [], $times = [], $searchable = [], $sort = null, $hideHeader = null, $hidePagination = null, $perPage = 10, $exportable = false, $hideable = false, $beforeTableSlot = false, $afterTableSlot = false, $params = [])

**Comment by Sandman83** [comment]
I assume this should go into params, no? Did you try something like ['id' => $params.id]
and override the mount method with appropriately? 
Maybe you will have to copy the content of the LivewireDatatable:mount method too or to call the parent method in an appropriate manner.

**Comment by rvigneshw** [comment]
Basically what I need to do is fetch records based on ID, for that I need to somehow pass ID into this component. I'm not sure how to do it?

**Comment by rvigneshw** [comment]
My builder method will be something like this,

`
public function builder()
 {
        return User::query()->where('gadget_id',$gadget_id); 
 }
`

**Comment by Sandman83** [comment]
I assume, you use builder to define the fields, not the restrictions. After that you use filters to restrict the results.

From what I understand (and tried out) the base class code you can override the activeSelectFilters property by 

$activeSelectFilters = [$columnNumber => [$gadget_id]];

Where $columnNumber is the zero-based number of the column with gadget ids. 

Now, the question still remains how to set the $gadget_id. Try passing it via the params array or automatically, as usual in Livewire.

**Comment by rvigneshw** [comment]
> Try passing it via the params array or automatically, as usual in Livewire.

Well I'm not sure how to do it? Do you any example similiar to this,
`@livewire('component', ['id' => $id])`

**Comment by Sandman83** [comment]
the default way is described here: 
https://laravel-livewire.com/docs/2.x/rendering-components#parameters

In the same section the approach via the mount method is described. But in the current case, the mount method is already used. So, you would have to alter your variable by ['id' => $params.id]. Didn't test the last one.

**Comment by rvigneshw** [comment]
Incase someone wondering how to do it. Here's what I did,

`<livewire:view-name :gadget_id="$gadget->id"/>`

In the livewire controller I did created a variable of same name and livewire will automatically assign the given value there,

` public $gadget_id;`

Then in conditional statement you can use something like,

`public function builder() { return User::query()->where('gadget_id',$this->gadget_id); }`

**Comment by stojankukrika** [comment]
@rvigneshw this didn't works for me always get null as value
