### ISSUE TITLE
Any plans for seclect rows

### ISSUE THREAD

**Issue by tanthammar** [MedicOneSystems/livewire-datatables#13]
Hi, great job with this package!!!!

Do you have any plans to add a checkbox to be able to select rows, like the kdion4891 package has?

**Comment by marksalmon** [comment]
Hi, thanks.

If I understand correctly, this would be a checkbox to select one or more rows and then have a public property on the component class that contained an array of the selected rows?

Sounds reasonable to me, I will take a look.

**Comment by tanthammar** [comment]
Exactly. The kdion package has the needed source Code.
