### ISSUE TITLE
Natural sort on column

### ISSUE THREAD

**Issue by WimDeMeester** [MedicOneSystems/livewire-datatables#142]
Hi,

Is it possible to sort a column using natural sort?  I have a list of astronomical objectnames, and I want them sorted like this:
- M 1
- M 2
- ...
- M 10
- M 11
- ..
- M 110

At this moment, they are sorted like this:
- M 1
- M 10
- M 100
- M 101
- ...

**Comment by Tedderouni** [comment]
Some of the answers on this page might help:

https://stackoverflow.com/a/4686887

There are quite a few answers that are all different, and seem to produce slightly different results depending on the data.

In my case, I got some interesting results with both of these:

- `sortBy('CAST(field_name as SIGNED INTEGER)')`
- `sortBy('LPAD(LOWER(mycol), 10,0)')`
