### ISSUE TITLE
Modify class of tr to change background

### ISSUE THREAD

**Issue by pitr82** [MedicOneSystems/livewire-datatables#144]
Hi, 
thanks for nice great datagrid. 
I need to change the background tr for certain data
Mayby add some callback to row?

**Comment by MattHadfield113** [comment]
I also need this for something we are working on, any ideas on this ?

**Comment by marksalmon** [comment]
There are methods for applying styles to rows and cells. ```rowClasses``` receives the ```$row``` and the [laravel loop variable](https://laravel.com/docs/8.x/blade#the-loop-variable) as parameters. ```cellClasses``` receives the ```$row``` and ```$column```

For example:
```php
public function rowClasses($row, $loop)
{
    return 'divide-x divide-gray-100 text-sm text-gray-900 ' . ($this->rowIsSelected($row) ? 'bg-yellow-100' : ($row->{'car.model'} === 'Ferrari' ? 'bg-red-500' : ($loop->even ? 'bg-gray-100' : 'bg-gray-50')));
}

public function cellClasses($row, $column)
{
    return 'text-sm ' . ($this->rowIsSelected($row) ? ' text-gray-900' : ($row->{'car.model'} === 'Ferrari' ? ' text-white' : ' text-gray-900'));
}
```

**Comment by grafxflow** [comment]
This works with changing the styles but **'dark:'** styles don't seem to change with tailwind?
