### ISSUE TITLE
Preview file

### ISSUE THREAD

**Issue by lalov** [MedicOneSystems/livewire-datatables#15]
Hi, very nice package!

In the service provider you are setting a named route:

        Route::get('/datatables/{filename}', [FileExportController::class, 'handle'])
            ->middleware(config('livewire.middleware_group', 'web'))
            ->name('livewire.preview-file');

This makes the file upload preview in other livewire components fail, as the TemporaryUploadedFile in LiveWire uses the same name. 

        return URL::temporarySignedRoute(
            'livewire.preview-file', now()->addMinutes(30), ['filename' => $this->getFilename()]
        );

When using the upload preview, it fails with HTTP 500, as it then makes a link to a preview file in the /datatables/  directory on the server instead of the /livewire/preview-file/ url.

**Comment by marksalmon** [comment]
Thanks, good catch. Fixed now.
