### ISSUE TITLE
BelongsTo with pivot table

### ISSUE THREAD

**Issue by mrahmadt** [MedicOneSystems/livewire-datatables#153]
Hello

I have a many to many relations and usually, with Laravel, I can get all the data of my model with the pivot data using the below command

`` 
$tickets = Ticket::with('themes')->findOrFail($id);
``

This will return for me Ticket data, Themes, data, and pivot data (I already coded the relations in the Models with the columns)

Now how can I do this with livewire-datatables ?

**Comment by Dioniggio** [comment]
> 
> 
> Hello
> 
> I have a many to many relations and usually, with Laravel, I can get all the data of my model with the pivot data using the below command
> 
> ` $tickets = Ticket::with('themes')->findOrFail($id);`
> 
> This will return for me Ticket data, Themes, data, and pivot data (I already coded the relations in the Models with the columns)
> 
> Now how can I do this with livewire-datatables ?

Hey,

Do you mean using builder?

public function builder()
{
    return User::query()
        ->leftJoin('planets', 'planets.id', 'users.planet_id')
        ->leftJoin('moons', 'moons.id', 'planets.moon_id')
        ->groupBy('users.id');
}

Im not sure if this is what you looking for.

**Comment by Dioniggio** [comment]
I'm also interested on this!

In my case I have Companies and Users and in my builder I have:

```
public function builder()
  {
      $usersFromCompany = Company::find(1)->company_users;
      return $usersFromCompany;
  }
```

Its returning a collection with models inside:

```
Illuminate\Database\Eloquent\Collection {#1390 ▼
  #items: array:2 [▼
    0 => App\Models\User {#1432 ▶}
    1 => App\Models\User {#1429 ▶}
  ]
}
```

But I get this error in the view:

BadMethodCallException
Method Illuminate\Database\Eloquent\Collection::getModel does not exist. (View: (PATH TO APP) \resources\views\livewire\datatables\datatable.blade.php) 

Can somebody help me with this? Thanks.

**Comment by tanlocit9** [comment]
I use callback method like this

```
Column::callback(['id'],function($id){

                return Model::find($id)->collection1;

            })->label('This is label 1'),

```
but the seccond callback have to use like this because of the contraint of collumn:

```
Column::callback(['id','another_field'],function($id){

                return Model::find($id)->collection2;

            })->label('This is label 2'),
```
It works but get duplicated statement (must find 2 time). Any idea ?

**Comment by Dioniggio** [comment]
I solved this with a query:

        $usersFromCompany = User::query()
            ->join('user_company', 'users.id', '=', 'user_company.user_id')
            ->join('companies', 'user_company.company_id', '=', 'companies.id')
            ->where('companies.id', '=', $this->company->id);

        return $usersFromCompany;
        
I hope it helps! Good luck.

**Comment by Ahmed-Elrayes** [comment]
> I solved this with a query:
> 
> ```
> public function builder()
> {
>     $usersFromCompany = User::query()
>         ->join('user_company', 'users.id', '=', 'user_company.user_id')
>         ->join('companies', 'user_company.company_id', '=', 'companies.id')
>         ->where('companies.id', '=', $this->company->id);
> 
>     return $usersFromCompany;
> }
> ```
> 
> I hope it helps! Good luck.

it's a good solution, but what if you're using polymorphic relations? it would be so hard....
till now i can't figure out a way to do it.

**Comment by clanofartisans** [comment]
> I solved this with a query:
> 
> ```
> public function builder()
> {
>     $usersFromCompany = User::query()
>         ->join('user_company', 'users.id', '=', 'user_company.user_id')
>         ->join('companies', 'user_company.company_id', '=', 'companies.id')
>         ->where('companies.id', '=', $this->company->id);
> 
>     return $usersFromCompany;
> }
> ```
> 
> I hope it helps! Good luck.

How or where is `$this->company` getting set inside of the builder() method? When I try to do something similar, I'm effectively getting an error message stating `Property [$company] not found on component`. Maybe I'm missing something obvious?

**Comment by ekadigitalmakers** [comment]
Hey @clanofartisans,

`$this->company` refers to a property on the component:

`public $company;`

You pass it like this:

`@livewire('components.my-component', ['company' => $company ])`

I hope it helps!

**Comment by RDuuke** [comment]
Hey @Dioniggio And how did they add the columns?

**Comment by ekadigitalmakers** [comment]
@RDuuke You have many examples on `https://livewire-datatables.com` , but basically you add columns like that:

```
public function columns()
    {
        return [
            Column::callback('title', function ($value) {
                return view('datatables::link', [
                    'href' => "/" . Str::slug($value),
                    'slot' => ucfirst($value)
                    ]);
            })
                ->label('Page')
                ->sortBy('id')
                ->defaultSort('asc'),

            Column::name('description')
        ];
    }
```

**Comment by RDuuke** [comment]
@ekadigitalmakers 
Yes that I know, what I say is how I access the information of the pivot table with an extra column to the two id's
https://laravel.com/docs/8.x/eloquent-relationships#retrieving-intermediate-table-columns
