### ISSUE TITLE
checkbox showing extra row for select all option

### ISSUE THREAD

**Issue by kksagar** [MedicOneSystems/livewire-datatables#156]
Column::checkbox('id') this colum working properly but first row showing select all checkbox in datatable, this should show in table heading, any solution for it......
![docsdatatable](https://user-images.githubusercontent.com/53617758/109184570-23e61800-77b5-11eb-889d-1fc898354a9f.png)
![docsdatatable](https://user-images.githubusercontent.com/53617758/109184608-2e081680-77b5-11eb-8965-10a697d03b59.png)

**Comment by EmmanuelAyTuz** [comment]
Publish blades (it will be in "resources\views\livewire\datatables") and I think merge lines (datatables.blade.php) 78 to 107 into lines 62 to 76 (datatables.blade.php).
1. Copy lines 85 to 90 (datatables.blade.php) after line 70 (datatables.blade.php).
2. Copy lines 93 to 103 (datatables.blade.php) after line 15 (header-no-hide.blade.php)
3. Delete lines 78 to 107.

If you don´t need the filters skip second step, try.

**Comment by kksagar** [comment]
Thanks for the reply, I will surely apply it soon and reply back, kindly
appreciate it if you found my concern important for the library.
