### ISSUE TITLE
EXPORT functionality in complex version doesn't work properly.

### ISSUE THREAD

**Issue by Triumfator-M** [MedicOneSystems/livewire-datatables#158]
Exporting seems to export ALL FILTERED RESULTS, regardless of which records are selected with checkmarks. $selected array is getting populated properly when individual records are selected with checkmarks, but clicking on EXPORT button ignores $selected array and exports ALL filtered records instead or all records if there are no filters applied.

You can easily replicate this issue in Complex demo version.

**Comment by marksalmon** [comment]
Fixed in next release
