### ISSUE TITLE
Export return empty value

### ISSUE THREAD

**Issue by wahyusaragih** [MedicOneSystems/livewire-datatables#160]
I have a lot of rainfall data with value = 0, but when I export it in excel the results are empty. It is important to know that the data is 0 mm not blank, how to handle it?

**Comment by vipertecpro** [comment]
> 
> 
> I have a lot of rainfall data with value = 0, but when I export it in excel the results are empty. It is important to know that the data is 0 mm not blank, how to handle it?

Could you please more elaborate with screenshot and code ?

**Comment by marksalmon** [comment]
You can fix this by adding an ```exportCallback```:

```php
NumberColumn::name('rainfall')
    ->filterable()
    ->exportCallback(function ($value) {
        return (string) $value;
    });
```

https://github.com/MedicOneSystems/livewire-datatables#callbacks
