### ISSUE TITLE
Prefetch of sort() method

### ISSUE THREAD

**Issue by dietercoopman** [MedicOneSystems/livewire-datatables#163]
When i hover over my table headers i see backend calls in my network tab.  This is because of a wire::click.prefetch=sort i think. Is that prefetch an added value ? It feels a little bit uncomfortable to see that backend calls without even sorting the table.  Maybe i decide not to sort at all.

**Comment by underdpt** [comment]
You can publish the blade templates and delete all `.prefetch` from `resources/views/livewire/datatables/*`, this is what i did.
