### ISSUE TITLE
Error 404 when click paginate or search

### ISSUE THREAD

**Issue by mouragilvan** [MedicOneSystems/livewire-datatables#168]
Hello,
Im following this tutorial: https://www.webslesson.info/2020/10/datatables-with-livewire-in-laravel-8.html

But when i click in paginate or search, returns this error:

![image](https://user-images.githubusercontent.com/29922672/111055184-09b56680-8452-11eb-8986-0c9b3815d003.png)

**Comment by marksalmon** [comment]
Sorry, I don't know anything about that tutorial
