### ISSUE TITLE
Print only logged in users items

### ISSUE THREAD

**Issue by Tony-The-Developer** [MedicOneSystems/livewire-datatables#173]
Hello, Our old controller would use   $tasks = auth()->user()->tasks(); to print out the currently logged in users table entries. But after switching to livewire how would we do that. Because we have to use     public $model = Tasks::class;. So where would the auth part go.

**Comment by amit-viacon** [comment]
Use [global scope](https://laravel.com/docs/8.x/eloquent#global-scopes)

Example to filter tasks that belongs to the current user:
```php
    protected static function booted()
    {
        static::addGlobalScope('owner', function (Builder $builder) {
            $builder->where('user_id', Auth::user()->id);
        });
    }
```

> You need to add this inside Task model
