### ISSUE TITLE
Exporting values when columns are editable

### ISSUE THREAD

**Issue by 3141bishwa** [MedicOneSystems/livewire-datatables#174]
Anyone know any way to get column values when some columns are editable? Right now, I have a column

`NumberColumn::name('rate')->label('Rate')->editable()`

but when I try to export the table, I get a big chunk of HTML in the cells under the Rate column in my Excel file.

**Comment by 3141bishwa** [comment]
Also. I was using some of the solutions from #93 to format my exports to get correct header names.

**Comment by vipertecpro** [comment]
Please resolve this
