### ISSUE TITLE
can I change the css to support bootstrap

### ISSUE THREAD

**Issue by vincentmikhael** [MedicOneSystems/livewire-datatables#181]

**Comment by EmmanuelAyTuz** [comment]
Yes, if you need views, you can try this https://github.com/EmmanuelAyTuz/Views-BS4-Livewire-Datatable

**Comment by maximusblade** [comment]
@EmmanuelAyTuz  Yo yo
Can you give some guidance on how to get this working?

**Comment by EmmanuelAyTuz** [comment]
Is easy, you must copy the blades in resources\views\livewire\datatables

**Comment by marksalmon** [comment]
Nice. Thanks @EmmanuelAyTuz
