### ISSUE TITLE
CONCAT_WS and database drivers different from MySQL and Postgres

### ISSUE THREAD

**Issue by robertogallea** [MedicOneSystems/livewire-datatables#183]
I noticed a problem using callback columns. In particular those used the SQL function `CONCAT_WS` which is defined only for some dbms (e.g. MySQL, Postgres), but not others (e.g. Oracle, SQLite). 

Any chance this could be get fixed?

Great job anyway.

**Comment by marksalmon** [comment]
I have no experience with those DB drivers, but would accept a PR to fix this
