### ISSUE TITLE
Multiple relationship with same table is showing wrong values

### ISSUE THREAD

**Issue by amit-viacon** [MedicOneSystems/livewire-datatables#187]
### This fileds are fetching two different relationships
```php
Column::name('assignedBy.first_name')->label('Assigned by')->alignCenter(),
Column::name('assignedTo.first_name')->label('Assigned to')->alignCenter(),
```

### Both data is coming from same table (users)
```php
public function assignedBy()
{
    return $this->belongsTo(User::class);
}

public function assignedTo()
{
    return $this->belongsTo(User::class);
}
```

### **Problem:** The data-table is showing same value on both places

```sql
select `tasks`.`id` as `id`, `users`.`first_name` as `assignedBy.first_name`, `users`.`first_name` as `assignedTo.first_name` from `tasks` left join `users` on `tasks`.`assigned_by_id` = `users`.`id` where `tasks`.`deleted_at` is null order by `id` desc limit 10 offset 0
```

**Comment by ddjikic** [comment]
i have the exact same issue

**Comment by johnneijzen** [comment]
I had the same issue but I just fixed it by called variable in the query instead with as something instead #257

**Comment by amit-viacon** [comment]
This issues is still there on the package. And this is clearly not an expected behavious based on how the packages configurations work.

#257 is more of an hack and not "a fix".

**Comment by marksalmon** [comment]
Awaiting your PR, Amit.

**Comment by amit-viacon** [comment]
Sure. I'll try. But don't close your eyes to say that there is no issue.

It is a great package but it's having lots of issues.
