### ISSUE TITLE
Editable 1062 Duplicate entry

### ISSUE THREAD

**Issue by mafalda2007** [MedicOneSystems/livewire-datatables#189]
Hi, when use:

_livewire/users.php_
...

```
public function columns()
return [
Column::name('email')->label('E-Mail')->truncate()->filterable()->searchable()->editable(),
];
```
...

If field is changed by email existing. Show error by Duplicate entry .
The email field of my table has the unique property

How should I validate that Unique: email?

**Comment by marksalmon** [comment]
You could override the `edited` method from here:

[https://github.com/MedicOneSystems/livewire-datatables/blob/master/src/Traits/WithCallbacks.php](https://github.com/MedicOneSystems/livewire-datatables/blob/master/src/Traits/WithCallbacks.php)

or publish and edit the `editable.blade.php` template or use the `view` method to pass your own editable template and deal with the validation and persistence however you like.
