### ISSUE TITLE
Complex queries?

### ISSUE THREAD

**Issue by spekulatius** [MedicOneSystems/livewire-datatables#19]
Hello,

would this allow to build more complex queries for one column? 

E.g. filter "Name" by "Steve" AND NOT ("Jobs" OR "Ballmer")

Cheers,
Peter

**Comment by marksalmon** [comment]
Hi Peter,

Not quite. At the moment, the text search will split by space and perform an OR search on the column. 

I do have plans to add a complex query builder though, so watch this space...

**Comment by spekulatius** [comment]
Awesome, sounds good. Feel free to tag me once it is released
