### ISSUE TITLE
Question: how do we take multiple Models with relationships?

### ISSUE THREAD

**Issue by Morpheus-ro** [MedicOneSystems/livewire-datatables#190]
I am working on implementing this package but in this moment the presented solution with Column::scope with filterable scope seems not to be the best one. Imagine that I have a model with more than 20 relationships and some of them I need to show in the datatable. If I start from the model User I end up populating this model and maybe others also with 2 x number of relations just for this to work ... Does anyone have a better way to do this? Maybe the native Laravel Eloquent way (User::with('....')->get()->map() ... etc)?

Thank you for any hint over this.

**Comment by marksalmon** [comment]
I don't know a better way. Thats why I made it this way. Happy to consider PRs.
