### ISSUE TITLE
Question: Use Encryptable Trait

### ISSUE THREAD

**Issue by JacAppDev** [MedicOneSystems/livewire-datatables#191]
Hey,

i'm using a Trait to decrypt encrypted Data from the Database in Models.
Unfortunately Datatables isn't checking against the Model if there is Data from the DB which needs to be encrypted before showing, sorting or filtering.

Maybe i'm missing something but is there a way to do that?

Thanks!

**Comment by marksalmon** [comment]
Datatables doesn't use eloquent, so things like this need to be done 'manually'

```php
Column::callback('first_name', function ($first_name) {
    return decrypt($first_name);
})
```
