### ISSUE TITLE
Pagination does not appear

### ISSUE THREAD

**Issue by impactcolor** [MedicOneSystems/livewire-datatables#193]
When I load the livewire datatable it does not display the pagination: https://www.screencast.com/t/0pRzgTjNA6GD

Here is my code:
`<livewire:orders/>`

`namespace App\Http\Livewire;

use App\Models\Order;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\NumberColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class Orders extends LivewireDatatable
{
    public $model = Order::class;

    public function columns()
    {
      return [
          Column::name('inspection_date')
              ->label('Schedule Date')
              ->filterable()
              ->linkTo('user', 6),
          Column::name('address')
              ->label('Address')
              ->filterable()
              ->linkTo('user', 6),
          Column::name('city')
              ->label('City')
              ->filterable()
              ->linkTo('user', 6),
          Column::name('agent.name')
              ->label('Customer')
              ->filterable()
              ->linkTo('user', 6),
      ];
    }
}
`

Am I missing something?

**Comment by stojankukrika** [comment]
I have a same issue

**Comment by stojankukrika** [comment]
It looks like this line:
https://github.com/MedicOneSystems/livewire-datatables/blob/master/resources/views/livewire/datatables/datatable.blade.php#L152
If you remove hidden class all work awesome ;)

**Comment by stojankukrika** [comment]
Why this issue closed?

**Comment by marksalmon** [comment]
Can't reproduce. Maybe an issue with your tailwind setup.

Whatever the cause, publish the views and then do what you like.
