### ISSUE TITLE
linkTo on a relative path

### ISSUE THREAD

**Issue by diederikdr** [MedicOneSystems/livewire-datatables#196]
Fix:
diff --git a/src/Column.php b/src/Column.php
index bd162db..12c71f4 100644
--- a/src/Column.php
+++ b/src/Column.php
@@ -138,7 +138,7 @@ class Column
     {
         $this->callback = function ($value) use ($model, $pad) {
             return view('datatables::link', [
-                'href' => "/$model/$value",
+                'href' => url("/$model/$value"),
                 'slot' => $pad ? str_pad($value, $pad, '0', STR_PAD_LEFT) : $value,
             ]);
         };

**Comment by marksalmon** [comment]
OK
