### ISSUE TITLE
[Question] LinkTo another DataTable with setting activeTextFilters

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [MedicOneSystems/livewire-datatables#203]
Hello, at first i wanna thank you for this amazing library.
i was wondering is there a way to use LinkTo function to link column with another data table and set the values in activeTextFilters ?
as example i'm clicking on user id so i want it to direct me to users datatable and set in the active text filters the user id as a filter.
so it would only show this user .
is it possible using function LinkTo only?

**Comment by marksalmon** [comment]
I think the implementation will be very use-case specific but I think possible with existing features.

My first thought is that I would try to do it with the `view` method. 

Create a little widget view and use it to trigger a Livewire event that could be listened for by the second table and apply the filter:

```blade
<button wire:click="$emit('filter-user-table', {{ $value }}">{{ $value }}"</button>
```

If the second table is on a different page you will need to use some javascript

**Comment by Ahmed-Elrayes** [comment]
hmmm, thanks for the info, yesterday i got it to work by using get route and send the user id in it and send activeTextFilter data

like this 
```php
if ($this->filter_id) {
            $activeTextFilters = [
                '2' => [
                    $this->filter_id,
                ]
            ];
  }
```
since the column index is not dynamic i could do it this way so the column is always index 2 so it would filter it.
