### ISSUE TITLE
when column is editable mode, search results doesn't render correctly

### ISSUE THREAD

**Issue by parmonov98** [MedicOneSystems/livewire-datatables#224]
![image](https://user-images.githubusercontent.com/24564577/124378800-d6cb0300-dccc-11eb-95c9-6f737cf1ef5b.png)

**Comment by F-Yousri** [comment]
+1 here. same issue

**Comment by githesix** [comment]
Editable columns are wrapped into a button, and the content escaped by _htmlspecialchars_ in [editable.blade.php](https://github.com/MedicOneSystems/livewire-datatables/blob/c3ee9c1fcf663d5bb5649c3a1f2f15448641b811/resources/views/livewire/datatables/editable.blade.php) :
`<button class="w-full text-left hover:bg-blue-100 px-2 py-1 -mx-2 -my-1 rounded focus:outline-none" x-bind:class="{ 'text-green-600': edited }" x-show="!edit"
        x-on:click="edit = true; $nextTick(() => { $refs.input.focus() })">{!! htmlspecialchars($value) !!}</button>`

This function transforms < or > by &lt; and &gt; and breaks their correct rendering.

As a workaround, we can simply disable highlighting in **config/livewire-datatables.php** :
`'suppress_search_highlights' => true, // When searching, don't highlight matching search results when set to true`

**Comment by marksalmon** [comment]
Fixed

**Comment by jjmpsp** [comment]
This issue has returned but can confirm ```'suppress_search_highlights' => true``` has fixed the highlighting bug.

I had to run ```php artisan config:clear``` for the change to take effect.
