### ISSUE TITLE
Column filtering not working

### ISSUE THREAD

**Issue by lwits-arjay** [MedicOneSystems/livewire-datatables#228]
Not sure what happened but after i run "composer upgrade" column filter suddenly stop working.

**Comment by lwits-arjay** [comment]
Here's the error i get when trying to filter column
![image](https://user-images.githubusercontent.com/62975890/125085032-bcde5580-e0fc-11eb-9e55-fc680a830050.png)

**Comment by kd75000** [comment]
Same here.
Great package by the way !

**Comment by dhofstedt** [comment]
Same, recently ran composer upgrade and column filter is not working. Here are the package versions I think might be relevant:

laravel/framework v8.49.2
livewire/livewire v2.5.3
mediconesystems/livewire-datatables v0.4.3
alpinejs@2.8.1

**Comment by dhofstedt** [comment]
Saw on issue [232 ](https://github.com/MedicOneSystems/livewire-datatables/issues/232)that the latest livewire update fixed a problem with setting a filterable column.

So I ran composer update livewire/livewire, which automatically downgraded livewire-datatables:
![image](https://user-images.githubusercontent.com/20133294/125613934-41ea1cbe-3075-4f4c-8f7b-d51ffb34997e.png)

Then, after republishing the new livewire assets, the filter column behavior was the same. The selected filter values show up empty below the filter dropdown, and the column is not filtered:
![image](https://user-images.githubusercontent.com/20133294/125614252-3f93bd6c-3ba7-45b3-9914-c4f773e37cb7.png)

**Comment by amit-viacon** [comment]
Update livewire and republish assets

```sh
composer update livewire/livewire
php artisan livewire:publish --assets
```
