### ISSUE TITLE
Uncaught ReferenceError: $event is not defined

### ISSUE THREAD

**Issue by chongieball** [MedicOneSystems/livewire-datatables#232]
When I set filterable to column, got this error

```
Uncaught ReferenceError: $event is not defined
    at eval (eval at parseOutMethodAndParams (wire-directives.js:93), <anonymous>:6:21)
    at Directive.parseOutMethodAndParams (wire-directives.js:93)
    at Directive.get (wire-directives.js:58)
    at node_initializer.js:202
    at Component.value (index.js:562)
    at HTMLInputElement.<anonymous> (node_initializer.js:194)
```
How to solve this error? Thanks

**Comment by pepijndik** [comment]
I got the same error, everything was working fine untill i installed the project on my new labtop...

**Comment by pepijndik** [comment]
I think our issue is fixed in the newer version of livewire
https://github.com/livewire/livewire/releases/tag/v2.5.4
testing it right now

**Comment by pepijndik** [comment]
> I think our issue is fixed in the newer version of livewire
> https://github.com/livewire/livewire/releases/tag/v2.5.4
> testing it right now

This didn't fix the issue for me... Hope some one else has any idea how to fix this

**Comment by pepijndik** [comment]
> I think our issue is fixed in the newer version of livewire
> https://github.com/livewire/livewire/releases/tag/v2.5.5
> testing it right now

After republish everything for livewire this fixed the issue for me!

**Comment by amit-viacon** [comment]
Update livewire and republish assets

```sh
composer update livewire/livewire
php artisan livewire:publish --assets
```

**Comment by chongieball** [comment]
solve by update livewire version. thanks.
