### ISSUE TITLE
Undefined offset : ? 

### ISSUE THREAD

**Issue by chillman2101** [MedicOneSystems/livewire-datatables#233]
i don't know sometimes my livewire datatables always show this error, 
ErrorException
Undefined offset: 10 (View: /home/shoeseuh/public_html/shoeseuh/vendor/mediconesystems/livewire-datatables/resources/views/livewire/datatables/datatable.blade.php)

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php:374

and always pointed to this method

  public function getSortString()

    {

        $column = $this->freshColumns[$this->sort];
        
        ...
        
      }

**Comment by spoyntersmith** [comment]
I think this is to do with how the session variable gets set and retrieved, 10/10 clearing session removes the error for me which isn't ideal

https://github.com/MedicOneSystems/livewire-datatables/blob/bd73fec5cb5309d58d37224d198cd33d97394826/src/Http/Livewire/LivewireDatatable.php#L96

**Comment by sdon2** [comment]
Actually this is happening even in your own website...

![livewire-datatables](https://user-images.githubusercontent.com/3636658/126486577-baab7bdb-92fa-4a08-87ac-866302289a48.png)

**Comment by sdon2** [comment]
Thank you @spoyntersmith. Your pull request is fixing this issue. Hope update will be available soon in packagist.

**Comment by sdon2** [comment]
@spoyntersmith  Sorry my mistake. I have to update the "mediconesystems/livewire-datatables" version in composer.json from "0.5.1" to "dev-master".

**Comment by sdon2** [comment]
@spoyntersmith  But this commit makes unable to determine initial sorting order based on defaultSort function.

**Comment by sdon2** [comment]
@spoyntersmith I believe, setting ```public $sort = 'id|asc';``` in the datatable component is solving this issue. I have tested it.

**Comment by jacquestvanzuydam** [comment]
@sdon2 Logging out / clearing session cache fixes the issue. First thing I tried was setting the $sort variable, but that didn't fix it. @spoyntersmith 's pull request is likely the best way to get around this.

**Comment by spoyntersmith** [comment]
> @sdon2 Logging out / clearing session cache fixes the issue. First thing I tried was setting the $sort variable, but that didn't fix it. @spoyntersmith 's pull request is likely the best way to get around this.
> 
> Edit: Replied to last comment without reading previous. Apologies.

I can confirm, I've tried @sdon2 's method too, I still managed to trigger the error.
This tends to happen to me most when adding, changing columns in development (understandably, session vars set then columns change and that array key longer exists)
