### ISSUE TITLE
Layout CSS Broken

### ISSUE THREAD

**Issue by itxp2008** [MedicOneSystems/livewire-datatables#236]
Hi,

I don't know what's the problem, the rows are not listed horizontally, on previous versions worked fine.

![image](https://user-images.githubusercontent.com/7779966/125929161-b2c89303-2084-4ce4-b251-45417ddeb141.png)

`composer.json`

```
    "require": {
        "php": "^7.3|^8.0",
        "bugsnag/bugsnag-laravel": "^2.0",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel-notification-channels/telegram": "^0.5.1",
        "laravel/framework": "^8.40",
        "laravel/jetstream": "^2.3",
        "laravel/sanctum": "^2.6",
        "laravel/tinker": "^2.5",
        "livewire/livewire": "^2.5",
        "mediconesystems/livewire-datatables": "dev-master"
    },
```

`package.json`

   ```
 "devDependencies": {
        "@tailwindcss/forms": "^0.3.1",
        "@tailwindcss/typography": "^0.4.0",
        "alpinejs": "^3.0.6",
        "axios": "^0.21",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "postcss": "^8.1.14",
        "postcss-import": "^14.0.1",
        "tailwindcss": "^2.2.2"
    }

```

**Comment by itxp2008** [comment]
Chrome - works
iOS - works
Firefox - doesn't work

larasail environment http

changed to php artisan serve it works on firefox

Don't know the cause

**Comment by itxp2008** [comment]
Update: swithced to https on larasail end works on firefox...

**Comment by aldoadhi** [comment]
Got this exact issue recently. I solved it by running `npm run dev`.
I think it should be included in the installation guide.

**Comment by apsg** [comment]
I've got exactly the same problem - `npm run prod` produces broken styles
