### ISSUE TITLE
Division by 0 when routing with a param

### ISSUE THREAD

**Issue by JerryBels** [MedicOneSystems/livewire-datatables#237]
Hello guys. So I'm routing simply with a param:

```php
Route::get('/user/{userId}/animations', UserAnimations::class)
            ->name('users.animations');
```

And I simplified my component as much as possible : 

```php
class UserAnimations extends LivewireDatatable
{
    public $model = Animation::class;
    public $userId;

    public function columns()
    {
        return [
            NumberColumn::name('id')
        ];
    }
}
```

If I `dd($this->userId)` in the builder, it's here - the param is received as expected. 

Anyway, when I'm trying to load the page, I get a nice 

```
ErrorException
Division by zero (View: vendor/mediconesystems/livewire-datatables/resources/views/livewire/datatables/datatable.blade.php)
```

![image](https://user-images.githubusercontent.com/4408419/126882991-1422d6ec-aa50-4595-9ed9-aae60135a77e.png)

Also note, if I `dd($perPage)` in \Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable::mount - it's false. That's the issue - if I go and set `$this->perPage = $perPage ?: config('livewire-datatables.default_per_page', 10);` - replacing `??` by `?:`, it works. Although I'm practically sure there is an issue with the params function `mount` get. If I `dd($model)` it shows an empty array, like if it was "pushed" away from first place in the mount function by my variable and getting the empty array intended for `$include`, and `$perPage` is getting the `false` intended for `$exportable`...

**Comment by JerryBels** [comment]
Workaround : create a simple view with your layout tag and use the `params` anyways to send your data.

```
<livewire:user-animations params="{{$user->id}}" />
```

Works for me. Adds an useless file though.

**Comment by marksalmon** [comment]
I think this workaround is the best option at the moment.

I can't get my head round how to anticipate an optional route parameter in the mount method
