### ISSUE TITLE
callback with filterable not working  

### ISSUE THREAD

**Issue by ddjikic** [MedicOneSystems/livewire-datatables#239]
I am trying to add a filter on a column that has a callback and i want it to filter based on array key not array value but display array values in the drop down. 

> 

    Column::callback(
                [ 'role.id','extend.applies '],
                function ($role_id, $applies) {
                    $return =User::$roleNames[$role_id];
                    if ($role_id == User::ROLE1) {
                        $return .= ' ' . ($applies ?? 0) . ' ' . __('applies left');
                    }
                    return $return;
                }
     )->label(__('Role'))->filterable(  User::$roleNames )->searchable(),

>   
     select count(*) as aggregate 
     from `users` 
     left join `user_extends` on `user_extends`.`user_id` = `users`.`id` 
     left join `roles` on `users`.`role_id` = `roles`.`id` 
     where (((CONCAT_WS('|**lwdt**|' ,
                                            COALESCE(roles.name, ''),
                                            COALESCE(roles.id, ''), 
                                            COALESCE(user_extends.applies , '')
                       ) = 'Admin')))   
i think  the generated query is wrong 

Am I missing something or how can I resolve this?
thank you.

**Comment by marksalmon** [comment]
Hi @ddjikic,

I have added another column method called ```filterOn``` which allows you to specify SQL statements upon which to filter, so in your example you can now do:

```php
Column::callback([ 'role.id','extend.applies '], function ($role_id, $applies) {
    $return = User::$roleNames[$role_id];
     
    if ($role_id == User::ROLE1) {
        $return .= ' ' . ($applies ?? 0) . ' ' . __('applies left');
    }

    return $return;
})->label(__('Role'))
    ->filterable(User::$roleNames)
    ->filterOn('roles.name')
    ->searchable(),
```

**Comment by shahidkarimi** [comment]
@marksalmon what if `$roleNames are like [1=> 'Admin', 2 => 'User']`  and it the db stores 1 and 2.
