### ISSUE TITLE
How to select additional columns without adding them to the table?

### ISSUE THREAD

**Issue by Shadercloud** [MedicOneSystems/livewire-datatables#241]
How can I select additional columns from the model without having them added as a table column?  For example I want to add the model `part_id` to the `view()`, but currently the `view()` method only receives the `$value` of the current column and the `$row` which only contains visible other columns.

For example I have something like this:

```
    public function columns()
    {
        return [
            Column::name('part_name')->view('tables.partname'),
        ]
    }
```
How can I get the model ID inside my view?  If I add `part_id` as a separate column I can then get it from the `$row` inside of the view, but then it will be visible to users.

I tried setting up as a callback column, like this:
```
    public function columns()
    {
        return [
            Column::callback(['part_name', 'part_id'], function ($part_name, $part_id) {
                return view('tables.partname')->with([
                    'value' => $part_name,
                    'part_id' => $part_id
                ]);
            })
            ->defaultSort('asc')
            ->searchable()
            ->label('Part Name')
        ]
    }
```
But then it messes up the sort and search because it's trying to do it on a CONCAT() of both columns instead of just the `part_name`

**Comment by marksalmon** [comment]
I'm pretty sure your callback would work if you chained 
```php
->sortBy('part_name')
```
On to the end of it
