### ISSUE TITLE
Undefined property: stdClass::$tests.id

### ISSUE THREAD

**Issue by Tesla2k** [MedicOneSystems/livewire-datatables#242]
Hello,
I get the above error message in LivewireDatatable.php:970:

`                        'rowId' => $row->{$this->builder()->getModel()->getTable() . '.' . $this->builder()->getModel()->getKeyName()}, `

I have a simple test table with raw and editable:

    public $model = Test::class;

    public function columns()
    {
        return [
                NumberColumn::raw('testF')->editable(),
                NumberColumn::name('testI')
        ];
    }

testF is a float, testI an Integer

**Comment by marksalmon** [comment]
Thanks for the clear test example. Made it easy to reproduce.

The editable feature needs the model ID, which in the simple test table is not included anywhere in the select statement.

I have made a fix that I will include in the next release, but in the meantime you can work around this by including:

```php
NumberColumn::raw('tests.id')->hide(),
```

in your array of columns.

**Comment by Tesla2k** [comment]
Thank You, it worked!
