### ISSUE TITLE
NULL valus in editable fields cause the clickable area to be smaller than usual

### ISSUE THREAD

**Issue by Tesla2k** [MedicOneSystems/livewire-datatables#245]
Hello,
when I have a NULL value in a editable field, the hover and the clickable area to edit are smaller, than when a value is in the field:
It would be nice if they were the same.

NULL value:
![grafik](https://user-images.githubusercontent.com/9998533/128469351-2e30e0e9-bae2-49aa-9319-0b92b6032985.png)

Normal value:
![grafik](https://user-images.githubusercontent.com/9998533/128469385-4decf6a0-d532-4b3b-a0f1-887751b2b30a.png)

**Comment by marksalmon** [comment]
Thanks. Fixed for next release.
