### ISSUE TITLE
Problem with display of DataTable

### ISSUE THREAD

**Issue by theokafadaris** [MedicOneSystems/livewire-datatables#258]
Hi,
I installed in a new project the livewire-datatable and I see that there is a problem with display of table.
The colums are displayed one below the other.
I am using the following versions.
Laravel 8.54,
Livewire 2.5
Livewire-Datatables 0.5.4

Thanks!
Theo

**Comment by jacquestvanzuydam** [comment]
In your Taillwind config file, make sure your are including the vendor files for this repository for your production build.

**Comment by theokafadaris** [comment]
> In your Taillwind config file, make sure your are including the vendor livewire files for this repository for your production build.

Can you help me a little bit more where in tailwind.config.js file to put what?
Thanks in. advance!

**Comment by theokafadaris** [comment]
I just run `npm run prod` and the problem was resolved.
Thanks for your help!!!

**Comment by jacquestvanzuydam** [comment]
```

module.exports = {
    purge: {
      content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './vendor/mediconesyste/livewire-datatables/resources/livewire/**/*.blade.php',
        './storage/framework/views/*.php',
```

Apologies for the incomplete snippet I'm on my mobile at the moment.
