### ISSUE TITLE
i dont get why my defaultsort keep giving random behavior  

### ISSUE THREAD

**Issue by johnneijzen** [MedicOneSystems/livewire-datatables#260]
i used this library lot in my project but lately my client notice that the default sort is not working correctly and I am not sure what I am doing wrong

    public function columns()
    {
        return [
            NumberColumn::name('id')
                ->defaultSort('asc')
                ->label('JO Number')
                ->searchable(),

            Column::name('order.client.name')
                ->label('Client Name')
                ->searchable(),

            Column::name('order.client_contact_persons.contact_person')
                ->label('Client Contact Person')
                ->searchable(),

            Column::callback(['employee.first_name', 'employee.last_name'], function ($first_name, $last_name) {
                return $first_name . ' ' . $last_name;
            })->label('Artist Assigned')
                ->searchable(),

            Column::name('order.order_date')
                ->label('Order Date'),

            Column::name('order.due_date')
                ->label('Due Date')
                ->searchable(),

            Column::name('order.status')
                ->label('Status')
                ->searchable(),

            Column::name('order.payment_status')
                ->label('Payment Status')
                ->searchable(),

            Column::name('order.job_order_agent.name')
                ->label('Agent'),

            Column::name('created_user.name')
                ->label('Created By'),

            Column::name('updated_user.name')
                ->label('Updated By'),

            Column::callback('created_at', function ($created_at) {
                $dt = Carbon::parse($created_at);
                return $dt->format('Y-m-d H:i');
            })->label('Created At')
                ->searchable(),

            Column::callback('updated_at', function ($updated_at) {
                $dt = Carbon::parse($updated_at);
                return $dt->format('Y-m-d H:i');
            })->label('Updated At')
                ->searchable(),

            Column::callback(['order.due_date', 'order.status'], function ($due_date, $status) {
                return view('job_orders.due_date', ['due_date' => $due_date, 'status' => $status]);
            })->label('Over Due'),

            Column::callback(['id'], function ($id) {
                return view('job_orders.actions', ['id' => $id]);
            }),
        ];
    }

but everytime I reload page it jumps 
![image](https://user-images.githubusercontent.com/1343960/130199844-2e7856e1-cacc-473d-ac32-fe78c262aba1.png)

**Comment by andruu** [comment]
I'm having the same issue

**Comment by kirba** [comment]
The table is using prefetch option for livewire action

`wire:click.prefetch="sort('{{ $index }}')"`

so when you hover over some column the session value gets changed and on the next page reload you will experience sort change as well. For now to tackle this you can publish views and remove .prefetch option from the column button

@marksalmon I think you should remove the prefetch option entirely if session is being used. As stated in livewire docs

> Livewire offers the ability to "prefetch" the result of an action on mouseover. Toggling display content is a common use case.
This is useful for cases when an action DOES NOT (like writing to session or database) perform side effects. If the action you are "pre-fetching" has side-effects, the side-effects will be unpredictably executed.

**Comment by johnneijzen** [comment]
removing .perfetch does fix random jumping behavior but i taught default sort it is always default sort not only for the first time but it seems if sort column different then leave page then go back to table it save last sorted column

**Comment by johnneijzen** [comment]
oh wait it get store in session is there a way to remove this behavior or not, if not possible is also okay at least jumping behavior is fixed with your workaround

**Comment by marksalmon** [comment]
Good point @kirba.  I have removed prefetch from the sort triggers in v0.6.2.

@johnneijzen I would like to keep the session storage as I think it makes for good UX that the table remembers its last sorting when the user returns to it (in the same session). If its important to you we could add a config variable that prevents this behaviour, let me know.

**Comment by johnneijzen** [comment]
> Good point @kirba. I have removed prefetch from the sort triggers in v0.6.2.
> 
> @johnneijzen I would like to keep the session storage as I think it makes for good UX that the table remembers its last sorting when the user returns to it (in the same session). If its important to you we could add a config variable that prevents this behaviour, let me know.

that would be great if there was a config for it but same time it is not a big deal since mostly user would log out of the session after they are done for the day. also thanks for posting a fix for random sorting behavior

**Comment by feliperafael** [comment]
I'm having the same issue. I haven't found any solution yet

**Comment by silicahd** [comment]
Has anybody figured out this issue. None of the default sorting functions work. So if you try to always pull by created_at desc it will never work be default.
