### ISSUE TITLE
Columns should have context of the entire model, especially in the callback method.

### ISSUE THREAD

**Issue by andruu** [MedicOneSystems/livewire-datatables#262]
Right now columns are only aware of the `columns` that are selected. It would be great to get the entire model in the context of the model.

**Comment by marksalmon** [comment]
There is no concept of 'model' because we are using the query builder, not eloquent, to retrieve the items from the database. You therefore need to explicitly select columns. 

If you really need the model, you could do:

```php
Column::callback('id', function ($id) {
    $model = Model::find($id);

    // do stuff with model
});
```

**Comment by XaRhezX** [comment]
> There is no concept of 'model' because we are using the query builder, not eloquent, to retrieve the items from the database. You therefore need to explicitly select columns.
> 
> If you really need the model, you could do:
> 
> ```
> Column::callback('id', function ($id) {
>     $model = Model::find($id);
> 
>     // do stuff with model
> });
> ```

This method is not very effective, because it will ask for a new query for each row
