### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by wahyupratama18** [MedicOneSystems/livewire-datatables#263]
Is there any documentation about localization, example to Indonesian, or Japanese, etc? At least for date. Or using callback only? Thank you very much :)

**Comment by marksalmon** [comment]
There is no documentation because I have never had to do this before. Can you  give any examples of what you would like to achieve?

**Comment by Nelio-Bila** [comment]
I think he needs a possibility to change the lange according to the app config language
