### ISSUE TITLE
Highlighting feature not working properly when we have RTL text

### ISSUE THREAD

**Issue by ghambale** [MedicOneSystems/livewire-datatables#267]
Hi there,
When we type something in English on search field, it works properly.
but when we type some phrase in Persian or Arabic language, instead of highlighting phrase, it escapes whole phrase with related tag.
I typed a phrase in Persian and took an screenshot to describe this.
It seems that this problem is related to whole columns with RTL characters,
I tried to search numbers in LTR columns and it works properly but searching numbers in RTL fields did not work properly.
Is it a bug ?

![Screenshot 2021-08-24 at 00-45-32 Laravel](https://user-images.githubusercontent.com/5165298/130513961-da1522a8-ab81-4615-9f9c-d14493fec959.png)

**Comment by marksalmon** [comment]
It looks like the highlighting code has been applied in a RTL direction, so the span tags are the wrong way round and aren't working.

The quick fix might be to set ```'suppress_search_highlights' =>  false``` in the config.

I'm afraid I have no experience with RTL text, so I don't know how to re-write the highlight method to handle this properly, but would welcome a PR if you (or anyone else) know how to do it.

**Comment by ghambale** [comment]
What part of the source code should be re-write to fix this problem ? i mean what method or class ?

**Comment by ghambale** [comment]
Actually, i read the source code and found the cause of the bug.
i created a method to check the direction of search phrase ( LTR or RTL )
Is that possible to let me contribute and fix this bug ?

**Comment by marksalmon** [comment]
Yes! please do a PR
