### ISSUE TITLE
Package broken after update

### ISSUE THREAD

**Issue by samfrjn11** [MedicOneSystems/livewire-datatables#275]
I upgraded from 0.4.3 to the latest 0.6.4. I'm getting following exception:
`Method Illuminate\View\View::layoutData does not exist.`

The issue is introduced with the Complex query builder commit Complex query builder (#252)
https://github.com/MedicOneSystems/livewire-datatables/commit/1a2d833c1bbe7f06cb7a5a1f663290abbd7cdfa8

src/Http/Livewire/LivewireDatatable.php#1230:
in the render() method ->layoutData(['title' => $this->title]); was added to the return statement.

I can't find anything related to the layoutData() method on the view().

Laravel version: 8.58

**Comment by marksalmon** [comment]
Is your livewire version up-to-date? 

layoutData() method comes from Livewire:
https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout

**Comment by samfrjn11** [comment]
> Is your livewire version up-to-date?
> 
> layoutData() method comes from Livewire:
> https://laravel-livewire.com/docs/2.x/rendering-components#custom-layout

OMG.
layoutData was indeed introduced in laravel/livewire@v2.4.4.

Thank you so much!

**Comment by samfrjn11** [comment]
@marksalmon maybe the minimum version of laravel/livewire should be upgraded to 2.4.4 then?
