### ISSUE TITLE
Callback function not working with the model dialog 

### ISSUE THREAD

**Issue by stephen-morlex** [MedicOneSystems/livewire-datatables#279]
IF i want to edit a row of data callback not triggering the dialog model not get the ID of the data

**Comment by stephen-morlex** [comment]
But when i dd($variable) it opens the dialog model with the corresponding data

**Comment by marksalmon** [comment]
Please show your code and explain more clearly what is the desired/actual behaviour

**Comment by stephen-morlex** [comment]
### This is the start of component with the callback actions

`class Table extends LivewireDatatable
{

    public function builder()
    {
        return Department::query();
    }
    public function columns()
    {
        return [
            NumberColumn::name('id'),
            Column::name('name')->editable()->searchable(),
            // DateColumn::name('created_at')->filterable(),
            Column::callback(['id', 'name'], function ($id, $name) {
                return view('table-actions', ['id' => $id, 'name' => $name]);
            })
        ];
    }
}
`
### And this is my modal method
` private function resetCreateForm()
    {
        $this->name = '';
    }
    public function openModalPopover()
    {
        $this->isDialogOpen = true;
    }
    public function closeModalPopover()
    {
        $this->isDialogOpen = false;
    }`

### and this is the edit method


` 
 public function store()
    {
        $this->validate([
            'name' => 'required|string',
        ]);

        Department::updateOrCreate(['id' => $this->department_id], [
            'name' => $this->name,
        ]);
        //creating the an Item will cause an activity being logged
        $activity = Activity::all()->last();
        $activity->description; //returns 'created'
        $activity->subject; //returns the instance of the Item that was created
        $activity->changes; //returns ['attributes' => ['name' => 'original name', 'text' => 'Lorum']];
        session()->flash('message', $this->department_id ? 'Department updated!' : 'Department created!');

        $this->closeModalPopover();
        $this->resetCreateForm();
    }
  public function edit($id)
    {
        $this->openModalPopover();
        $department = Department::findOrFail($id);
        $this->department_id = $id;
        $this->name = $department->name;
    }`

**Comment by stephen-morlex** [comment]
I want the dialog modal to bw trigger when i click on the edit method so i can edit the data, Thanks

**Comment by marksalmon** [comment]
I still don't really understand what isn't working for you.

I have updated the demo site with a working example: https://livewire-datatables.com/actions

**Comment by stephen-morlex** [comment]
Okay nice, let me check it out.

**Comment by MichelSanchez290** [comment]
I have a problem when I reload the page and for a moment my modal windows are visible, what could be the problem?


This is my blade component delete-modal.blade.php

`
<div x-data="{ open: {{ isset($open) && $open ? 'true' : 'false' }}, working: false }" x-cloak
>
    
    <span x-on:click="open = true">
        {{ $trigger }}
    </span>

    <div x-show="open"
        class="fixed z-50 bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
        <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0"
            x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200"
            x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
            class="fixed inset-0 transition-opacity">
            <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
        </div>

        <div x-show="open" x-transition:enter="ease-out duration-300"
            x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
            x-transition:leave="ease-in duration-200"
            x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
            x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            class="relative bg-gray-100 rounded-lg px-4 pt-5 pb-4 overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full sm:p-6">
            <div class="hidden sm:block absolute top-0 right-0 pt-4 pr-4">
                <button @click="open = false" type="button"
                    class="text-gray-400 hover:text-gray-500 focus:outline-none focus:text-gray-500 transition ease-in-out duration-150">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>

            <div class="w-full">
                <div class="mt-3 text-center">
                    
                    {{$slot2}}

                    <div class="mt-10 flex justify-center">
                        
                        <span  x-on:click="open = false" x-bind:disabled="working">
                            {{$cancelbutton}}
                        </span>

                        
                        <span x-on:click="working = !working">
                            {{ $butonCls }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
`

Esta es mi vista

`
 <x-modal.delete-modal  >
        <x-slot name="trigger">
            <button wire:key="delete-{{ $id }}" class="p-1 text-red-600 rounded hover:bg-red-600 hover:text-white"><x-icons.trash /></button>
        </x-slot>

        <x-slot name="slot2">
            <div class="flex items-center justify-center content-center">
                <i class="fas fa-exclamation-triangle text-7xl text-yellow-500"></i>
            </div>

            <h3 class="mt-3 text-lg leading-6 font-bold text-gray-900">
             
            </h3>

            <div class="mt-2">

                <div class="mt-3 text-gray-700">
                   
                </div>

                <x-slot name="cancelbutton">
                    <x-buttons.red class="w-32 shadow-sm inline-flex justify-center items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white  hover:bg-red-700 focus:outline-none focus:border-red-700 focus:shadow-outline-teal active:bg-red-700 transition ease-in-out duration-150">
                        {{ __('No')}}
                    </x-buttons.red>
                </x-slot>

                <x-slot name="butonCls">
                    <span @click="open = false">
                        <x-buttons.blue  wire:click="deleteQuery('{{ $id }}')" class="w-32 shadow-sm inline-flex justify-center items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white hover:bg-gray-700 focus:outline-none focus:border-gray-700 focus:shadow-outline-teal active:bg-gray-700 transition
                            ease-in-out duration-150">
                                {{ __('Si')}}
                        </x-buttons.blue>
                    </span>
                </x-slot>

            </div>
        </x-slot>
    </x-modal.delete-modal>
`
and here I command to call my view in my livewire datatable

`
public function columns()
    {
        //
        return [
            Column::checkbox(),

            Column::name('TENombre')
                ->defaultSort('asc')
                ->searchable()
                ->label('Nombre'),

            Column::callback(['id', 'TENombre'], function ($id, $TENombre) {

                    return view('livewire.admin.tematica.delete.delete-tematica', ['id' => $id, 'TENombre' => $TENombre]);
            })->label('Acciones')->unsortable()->excludeFromExport(),


        ];
    }
`

**Comment by mrtorks** [comment]
> I have a problem when I reload the page and for a moment my modal windows are visible, what could be the problem?
> 
> 
> 
> 
> 
> This is my blade component delete-modal.blade.php
> 
> 
> 
> `
> 
> <div x-data="{ open: {{ isset($open) && $open ? 'true' : 'false' }}, working: false }" x-cloak
> 
> >
> 
>     
> 
>     <span x-on:click="open = true">
> 
>         {{ $trigger }}
> 
>     </span>
> 
> 
> 
>     <div x-show="open"
> 
>         class="fixed z-50 bottom-0 inset-x-0 px-4 pb-4 sm:inset-0 sm:flex sm:items-center sm:justify-center">
> 
>         <div x-show="open" x-transition:enter="ease-out duration-300" x-transition:enter-start="opacity-0"
> 
>             x-transition:enter-end="opacity-100" x-transition:leave="ease-in duration-200"
> 
>             x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0"
> 
>             class="fixed inset-0 transition-opacity">
> 
>             <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
> 
>         </div>
> 
> 
> 
>         <div x-show="open" x-transition:enter="ease-out duration-300"
> 
>             x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
> 
>             x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
> 
>             x-transition:leave="ease-in duration-200"
> 
>             x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
> 
>             x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
> 
>             class="relative bg-gray-100 rounded-lg px-4 pt-5 pb-4 overflow-hidden shadow-xl transform transition-all sm:max-w-lg sm:w-full sm:p-6">
> 
>             <div class="hidden sm:block absolute top-0 right-0 pt-4 pr-4">
> 
>                 <button @click="open = false" type="button"
> 
>                     class="text-gray-400 hover:text-gray-500 focus:outline-none focus:text-gray-500 transition ease-in-out duration-150">
> 
>                     <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
> 
>                         <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
> 
>                             d="M6 18L18 6M6 6l12 12" />
> 
>                     </svg>
> 
>                 </button>
> 
>             </div>
> 
> 
> 
>             <div class="w-full">
> 
>                 <div class="mt-3 text-center">
> 
>                     
> 
>                     {{$slot2}}
> 
> 
> 
>                     <div class="mt-10 flex justify-center">
> 
>                         
> 
>                         <span  x-on:click="open = false" x-bind:disabled="working">
> 
>                             {{$cancelbutton}}
> 
>                         </span>
> 
> 
> 
>                         
> 
>                         <span x-on:click="working = !working">
> 
>                             {{ $butonCls }}
> 
>                         </span>
> 
>                     </div>
> 
>                 </div>
> 
>             </div>
> 
>         </div>
> 
>     </div>
> 
> </div>
> 
> `
> 
> 
> 
> Esta es mi vista
> 
> 
> 
> `
> 
>  <x-modal.delete-modal  >
> 
>         <x-slot name="trigger">
> 
>             <button wire:key="delete-{{ $id }}" class="p-1 text-red-600 rounded hover:bg-red-600 hover:text-white"><x-icons.trash /></button>
> 
>         </x-slot>
> 
> 
> 
>         <x-slot name="slot2">
> 
>             <div class="flex items-center justify-center content-center">
> 
>                 <i class="fas fa-exclamation-triangle text-7xl text-yellow-500"></i>
> 
>             </div>
> 
> 
> 
>             <h3 class="mt-3 text-lg leading-6 font-bold text-gray-900">
> 
>              
> 
>             </h3>
> 
> 
> 
>             <div class="mt-2">
> 
> 
> 
>                 <div class="mt-3 text-gray-700">
> 
>                    
> 
>                 </div>
> 
> 
> 
>                 <x-slot name="cancelbutton">
> 
>                     <x-buttons.red class="w-32 shadow-sm inline-flex justify-center items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white  hover:bg-red-700 focus:outline-none focus:border-red-700 focus:shadow-outline-teal active:bg-red-700 transition ease-in-out duration-150">
> 
>                         {{ __('No')}}
> 
>                     </x-buttons.red>
> 
>                 </x-slot>
> 
> 
> 
>                 <x-slot name="butonCls">
> 
>                     <span @click="open = false">
> 
>                         <x-buttons.blue  wire:click="deleteQuery('{{ $id }}')" class="w-32 shadow-sm inline-flex justify-center items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white hover:bg-gray-700 focus:outline-none focus:border-gray-700 focus:shadow-outline-teal active:bg-gray-700 transition
> 
>                             ease-in-out duration-150">
> 
>                                 {{ __('Si')}}
> 
>                         </x-buttons.blue>
> 
>                     </span>
> 
>                 </x-slot>
> 
> 
> 
>             </div>
> 
>         </x-slot>
> 
>     </x-modal.delete-modal>
> 
> `
> 
> and here I command to call my view in my livewire datatable
> 
> 
> 
> `
> 
> public function columns()
> 
>     {
> 
>         //
> 
>         return [
> 
>             Column::checkbox(),
> 
> 
> 
>             Column::name('TENombre')
> 
>                 ->defaultSort('asc')
> 
>                 ->searchable()
> 
>                 ->label('Nombre'),
> 
> 
> 
>             Column::callback(['id', 'TENombre'], function ($id, $TENombre) {
> 
> 
> 
>                     return view('livewire.admin.tematica.delete.delete-tematica', ['id' => $id, 'TENombre' => $TENombre]);
> 
>             })->label('Acciones')->unsortable()->excludeFromExport(),
> 
> 
> 
> 
> 
>         ];
> 
>     }
> 
> `

You might want to implement `x-cloak` if that's happening.
