### ISSUE TITLE
Possible to access model/row from callback?

### ISSUE THREAD

**Issue by zyxxyzyxz** [MedicOneSystems/livewire-datatables#28]
I've got some methods on my model to help with returning complex strings that depend on database information and such.
Is it possible for us to get access to the instance of the model so that I can access the functions I want to call?

For example;
```php
Column::callback('column', function ($model) {
    return $model->orderDetails();
})->label('Description')
```

Or

```php
Column::callback('column', function ($model) {
    return "{$model->name} - {$model->description}";
})->label('Description')
```

I think this would be incredibly useful, but I'm not sure if it's possible or not code wise.

**Comment by marksalmon** [comment]
The datatables class uses QueryBuilder to get the data and does not rehydrate the Eloquent models so it is not possible to call model methods directly. 

You would have to rehydrate the model in the callback like this

```php
Column::callback('id', function ($id) {
    return Model::find($id)->orderDetails();
})->label('Description')
```

**Comment by rawilk** [comment]
I ran into the same issue with needing the Model instances. I ended up creating my own base table class that extends the `LivewireDatatable` class from this package. On my base class, I overrode the `getQuery` method to force the query builder to query and return model instances instead:

```php
class Table extends LivewireDatatable
{
    protected bool $queryWithModelInstances = true;

    public function getQuery()
    {
        $this->buildDatabaseQuery();

        return $this->queryWithModelInstances
            ? $this->query
            : $this->query->toBase();
    }
}
```

@marksalmon I'd be happy to submit a PR if this kind of change is something you'd be interested in.

**Comment by underdpt** [comment]
Hi @rawilk 

I like your solution, but I don't see how you get the model on `Column::callback()`
