### ISSUE TITLE
too few argument

### ISSUE THREAD

**Issue by bananneAle** [MedicOneSystems/livewire-datatables#283]
hi, after and upgrade of livewire-datatable i get this error

`Too few arguments to function App\Http\Livewire\mostrautente\LavoriCreatorData::App\Http\Livewire\mostrautente\{closure}(), 1 passed in /home/bananne/Documenti/GitHub/evox-dashboard/vendor/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php on line 1327 and exactly 3 expected (View: /home/bananne/Documenti/GitHub/evox-dashboard/resources/views/livewire/datatables/datatable.blade.php)
`

in a datatable which it was working before the upgrade

any suggestion?

i was using the 0.4.3 version and now the 0.6.6

**Comment by marksalmon** [comment]
Try deleting and re-publishing the blade templates

**Comment by bananneAle** [comment]
> Try deleting and re-publishing the blade templates

doesn't work for me

**Comment by emageint** [comment]
and me too

**Comment by bananneAle** [comment]
the problem seems to be there
`$row->$name = $this->callbacks[$name](...explode(static::SEPARATOR, $value));`
on line 1327 of LivewireDatatable.php file

**Comment by marksalmon** [comment]
Fixed in v0.6.7
