### ISSUE TITLE
Filtering computed column with select box key => value

### ISSUE THREAD

**Issue by marionjiroff** [MedicOneSystems/livewire-datatables#284]
Hi, my issue is exactly this one : https://stackoverflow.com/questions/69124145/livewire-datatables-transform-column-and-filter

I have a computed column based on an id, and it displays the name associated to the id (the name is not in the DB). I want to filter this column data with a select box with key => value, and send the id instead of the value. I didn't find any clue on the net, can someone tell me if it is possible?
Thanks a lot in advance for your help!

Here is the code : 
`Column::callback(['Contact.idType'], function ($idType) {
        return self::$contactType[$idType];
    })->label('Type')->filterable(
        self::$contactType
    )
    ->searchable(),`

**Comment by marksalmon** [comment]
This should be possible, by passing either an associative array or an object with parameters 'id' and 'name' to the filterable method:

```php
Column::callback(['Contact.idType'], function ($idType) { 
    return self::$contactType[$idType]; 
})->filterable(collect(self::$contactType)->map(function ($value, $key) {
    return ['id' => $key, 'name' => $value];
})->label('Type')
    ->searchable(),
```

**Comment by marionjiroff** [comment]
Thanks a lot it works perfectly, could it be added in the documentation?
