### ISSUE TITLE
Error too few arguments when calling link method on Column

### ISSUE THREAD

**Issue by marionjiroff** [MedicOneSystems/livewire-datatables#285]
Hello everyone,
I have this error when I'm calling static link method on Column: Too few arguments to function Mediconesystems\LivewireDatatables\Column::Mediconesystems\LivewireDatatables\{closure}(), 1 passed in /laravel/packages/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php on line 1327 and exactly 2 expected

Here is the code : `Column::callback(['id'], function ($id) {
                return $id;
            })
            ->unsortable()
            ->link(
                '/myurl/{{id}}',
                'edit'
                )`

Maybe linked to https://github.com/MedicOneSystems/livewire-datatables/issues/283 ?

Any idea? Thank you very much

**Comment by marksalmon** [comment]
Try deleting and re-publishing the blade templates

**Comment by marionjiroff** [comment]
Thank you! I have another problem but not the same :)
