### ISSUE TITLE
Unable to use link method because of the {{caption}}

### ISSUE THREAD

**Issue by marionjiroff** [MedicOneSystems/livewire-datatables#290]
Hi everyone,
I'm using a link column like this : `Column::callback(['idType'], function ($idType) { return $idType; })
            ->unsortable()->link('/myurl/edit/{{idType}}', 'edit'),`

The link is not properly rendered, it looks like /myurl/edit/{{idType}}, as {{idType}} is not transformed as expected.
When I write `Column::callback(['idType'], function ($idType) { return $idType; })
            ->unsortable()->link('/myurl/edit/{{caption}}', 'edit'),`
it works... 

I looked into link method but $row is not an array and it seems it doesn't contain the row values as expected.

any idea? Thanks a lot

**Comment by guywarner** [comment]
@marionjiroff change it to:

`->callback(['idType'], function ($idType) { return "<a href='/myurl/edit/{$caption}">edit</a>)`

You're attempting to use blad syntax. You can also look up using actions.
