### ISSUE TITLE
Is there a bootstrap version of the package?

### ISSUE THREAD

**Issue by atoaugustyn** [MedicOneSystems/livewire-datatables#291]

**Comment by thyseus** [comment]
Yes, i  have used https://github.com/EmmanuelAyTuz/Views-BS4-Livewire-Datatable with great success.
We even still use bootstrap 3 and it took me just 5 minutes to adjust the provided views to my use case.
Its easy to adjust the views to your taste, just dont get overwhelmed by the first look of the view files.
