### ISSUE TITLE
issues with Column::callback in new release v0.6.7

### ISSUE THREAD

**Issue by Sajjad-Arjmand** [MedicOneSystems/livewire-datatables#296]
Column::callback is not working properly with more than 1 column.

``
Column::callback(['person_type', 'user_id'], function ( $person_type, $user_id ) {
                $user = PersonInfo::where('UserID', $user_id)->first();
                return $user->pfname . ' ' . $user->plname;
            })->alignCenter()->unsortable()
``

it says trying to get pfname from a non-object because $user_id is "" while it has value and if I access it using eloquent returns it's value

btw the callback function works perfect in version 0.6.6 so I downgraded it to v0.6.6

**Comment by esglobal** [comment]
Same issue here. Downgraded to v0.6.6 as well

**Comment by thyseus** [comment]
This issue is known and is currently being worked on. temporary hotfix:
https://github.com/MedicOneSystems/livewire-datatables/pull/297/files/049d02d60c592b2ff325737d8e1bd27f6f52bc4c#diff-413c9df1c279e92fce44ff152ed9ed1dc0a9fc87ca94fedf292b5f0de5121e4fR282

**Comment by marksalmon** [comment]
Fixed in v0.6.8
