### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by ousid** [MedicOneSystems/livewire-datatables#30]
I started using a laravel-datatables today and noticed that there is no RTL support in the package, are there any plans to support it?
If there is anything I can do to help add support for directions in the package, I will be happy to help

**Comment by marksalmon** [comment]
Can you give me some examples of what you mean by RTL support. I have no experience in this area.

**Comment by ousid** [comment]
RTL (Right To Left)  means the way how the design looks like and the way of writing a language such as the Arabic language  

![datatable-rtl](https://user-images.githubusercontent.com/21012933/92721402-f66bf600-f35d-11ea-9312-71a938559618.png)

**Comment by marksalmon** [comment]
I see. How did you generate that screenshot and what specifically do I need to change?

**Comment by ousid** [comment]
I made this screenshot from exisitting project I'm working on it,and I made some adjustments to `datatable` classes and if you wanted I could do a PR

**Comment by marksalmon** [comment]
Yes please do make a PR so that I can try to make the RTL option available to everybody. It is awesome to see my datatables being used with the Arabic language. 👍

**Comment by ousid** [comment]
Working on it
