### ISSUE TITLE
Failed to find and edit a column

### ISSUE THREAD

**Issue by daniieljc** [MedicOneSystems/livewire-datatables#309]
When a field in the table has edit and search assigned, it is mixed with the style applied by the search engine and appears with the span tag in yellow

![image](https://user-images.githubusercontent.com/36238313/135316793-6093166a-477c-4438-a556-f9bf770fda4f.png)

**Comment by marionjiroff** [comment]
Hi, could you write here your code please?

**Comment by marionfromfrance** [comment]
I have the same issue when I make a search on a searchable and editable column. Don't have it when I filter, only when I search with global field. Can you use filterable while waiting for the bug to be fixed?
