### ISSUE TITLE
Disable sorting for a specific column?

### ISSUE THREAD

**Issue by marbuser** [MedicOneSystems/livewire-datatables#31]
Certain columns I don't want to be sortable. Is this possible to achieve already or is this not currently possible?

**Comment by marksalmon** [comment]
Yep. Good suggestion. Its on the list. 😙

**Comment by Jurets** [comment]
Yes, I also need an "unsortable" - for action column! 
Although it seems, that such example in demo is working properly - action column header isn't clickable 
And it's strange )) https://livewire-datatables.com/actions
