### ISSUE TITLE
Loading indicator (Wheel) continuing to rotate after the data are display

### ISSUE THREAD

**Issue by tech62** [MedicOneSystems/livewire-datatables#330]
Hello,
I've include the livewire component in a blade view according the doc `<livewire:leaves-table  exportable />`

But when the page is loaded, the loading indicator (Wheel) continuing to rotate
![image](https://user-images.githubusercontent.com/16237642/138884153-fc87b013-7e64-4ec4-8486-e7c98a1c0700.png)

I've an error in markup.js line 412:19
`  setAttributeForElement(id, name, value) {
    if (this.content) {
      this.content.setAttributeForElement(id, name, value);
    }
  },`

`Valeur NaN inattendue lors de l’analyse de l’attribut y1.`
`Valeur NaN inattendue lors de l’analyse de l’attribut y2.`
`Valeur NaN inattendue lors de l’analyse de l’attribut x1.`
`Valeur NaN inattendue lors de l’analyse de l’attribut x2.`

Thanks for your help !

**Comment by bbarclay** [comment]
Same error and the table just won't render, all tools are broken.

**Comment by sort72** [comment]
A solution for this? I'm facing the same problem and nothing appears on js console / laravel logs

**Comment by Sicklou** [comment]
@sort72 
Did you have included the livewireScripts & livewireStyles ?

I got the same issue and it was because I forgot to set them.

See docs : https://laravel-livewire.com/docs/2.x/installation

**Comment by sort72** [comment]
> @sort72 Did you have included the livewireScripts & livewireStyles ?
> 
> I got the same issue and it was because I forgot to set them.
> 
> See docs : https://laravel-livewire.com/docs/2.x/installation

Yes, that was the issue, I forgot to add livewireScripts. Thanks!
