### ISSUE TITLE
Customise pagination dropdown options (to hide 'All' option)

### ISSUE THREAD

**Issue by grafxflow** [MedicOneSystems/livewire-datatables#347]
Is it possible to customise pagination dropdown options since I don't want the option of 'All'?

**Comment by gzai** [comment]
it's possible.
If you already publish the config file and blade template assets. 
```
php artisan vendor:publish --provider="Mediconesystems\LivewireDatatables\LivewireDatatablesServiceProvider"
```
open file ``resources/views/livewire/datatables/datatable.blade.php`` and comment in line 171
```
// <option value="99999999">{{__('All')}}</option>
```

**Comment by grafxflow** [comment]
Perfect :) 

Thanks for your help!
