### ISSUE TITLE
export options

### ISSUE THREAD

**Issue by Alezter** [MedicOneSystems/livewire-datatables#349]
Do you have any plan on adding more options on exporting? Like adding custom filename and styling?

I actually manage to do this by changing this line from ```LivewireDatatable.php```
```
return Excel::download(new DatatableExport($results), 'DatatableExport.xlsx');
```
to
```
return Excel::download(new DatatableExport($results), (!empty($this->filename) ? $this->filename.'.xlsx' : 'DatatableExport.xlsx' ));
```
then declaring it to my own Datatable for changing the filename. As for the styling I edited the ```DatatableExport.php``` and add some simple styling like auto width and bold header after reading the Documents for Laravel Excel.

My problem is, my changes would be deleted once I updated the package, right? since I'm editing a file from vendor (correct me if I'm wrong) so it would be nice if you could add this enhancement officially.

Really great package by the way.

**Comment by Elshaden** [comment]
What I do is Added the same Export Method from LivewireDatatable to my Component and change it how I want, no need to customize the LivewireDatatable  class, because when updated in Github you loose your changes.

I only changed the Exportable class used.

```
 return Excel::download(new **ExtendedDatatableExport**($results), $this->MyFileName.'.xlsx');

```

**Comment by Alezter** [comment]
> What I do is Added the same Export Method from LivewireDatatable to my Component and change it how I want, no need to customize the LivewireDatatable class, because when updated in Github you loose your changes.
> 
> I only changed the Exportable class used.
> 
> ```
>  return Excel::download(new **ExtendedDatatableExport**($results), $this->MyFileName.'.xlsx');
> ```
