### ISSUE TITLE
The search filter on the datatable persist when i display on other page with another datatable. 

### ISSUE THREAD

**Issue by mickael-dadoun** [MedicOneSystems/livewire-datatables#358]
Hi, my issues is : 
The second (or other) datatable is filtering with the search of the first datatable displayed (datatable with another model).
How reset it when i call another route ? 
Where are stocked the search param ?

thanks.

**Comment by thyseus** [comment]
Hey, @mickael-dadoun 

thanks for reporting this issue. I have implemented the persistance feature and will look into this issue in the next days; need to touch livewire-datatables anyway for some features in one of my projects.

**Comment by thyseus** [comment]
Please see if https://github.com/MedicOneSystems/livewire-datatables/pull/360 fixes the issue.

Note that you need to give every datatable a unique name via the `name` attribute as described in the `README.md` there.

**Comment by mickael-dadoun** [comment]
it's work.
Thanks.
