### ISSUE TITLE
Dependency conflict with Livewire 2.1

### ISSUE THREAD

**Issue by ChrisCook1906** [MedicOneSystems/livewire-datatables#36]
I installed a fresh Laravel instance with Laravel 8 + Jetstream.  I get the following conflict error in Composer:

Problem 1
    - Can only install one of: livewire/livewire[1.x-dev, v2.1.3].
    - Can only install one of: livewire/livewire[v2.1.3, 1.x-dev].
    - Can only install one of: livewire/livewire[1.x-dev, v2.1.3].
    - mediconesystems/livewire-datatables v0.3.1 requires livewire/livewire ^1.2 -> satisfiable by livewire/livewire[1.x-dev].
    - Installation request for mediconesystems/livewire-datatables ^0.3.1 -> satisfiable by mediconesystems/livewire-datatables[v0.3.1].
    - Installation request for livewire/livewire (locked at v2.1.3, required as ^2.0) -> satisfiable by livewire/livewire[v2.1.3].

**Comment by marksalmon** [comment]
I am working on the upgrade, it is pushed to the master branch but not
tagged yet because I need to do a little more testing. If you want to help,
try the master branch and let me know if it works.

**Comment by jongravois** [comment]
I installed with ```composer require mediconesystems/livewire-datatables:dev-master``` and it worked.

**Comment by ahosker** [comment]
Tried dev-master and working great.
