### ISSUE TITLE
Install Issue on Laravel 9

### ISSUE THREAD

**Issue by Markwow** [MedicOneSystems/livewire-datatables#392]
I am running into an issue installing on Laravel 9: 

  Problem 1
    - Root composer.json requires mediconesystems/livewire-datatables ^0.6.8 -> satisfiable by mediconesystems/livewire-datatables[v0.6.8].
    - mediconesystems/livewire-datatables v0.6.8 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).

Is it possible to add require ^9.0?

**Comment by thyseus** [comment]
https://github.com/MedicOneSystems/livewire-datatables/pull/390
