### ISSUE TITLE
laravel 9 doesn't support livewire-datatable package

### ISSUE THREAD

**Issue by yassermohammad** [MedicOneSystems/livewire-datatables#398]
Thank you good package,
I installed Laravel 9 and it does not support your package.
Please fix it.

  Problem 1
    - Root composer.json requires mediconesystems/livewire-datatables ^0.6.8 -> satisfiable by mediconesystems/livewire-datatables[v0.6.8].
    - mediconesystems/livewire-datatables v0.6.8 requires illuminate/support ^7.0|^8.0 -> found illuminate/support[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by thyseus** [comment]
Please use `dev-master` instead of the package provided by packagist and it should work with laravel 9.

**Comment by thyseus** [comment]
`0.7.0` published at packagist.
