### ISSUE TITLE
Feature Request: Add a Column to LiveWire $queryString

### ISSUE THREAD

**Issue by ahosker** [MedicOneSystems/livewire-datatables#40]
The `filterable(['type1','type2])` in this package is fantastic. 

I want the URL to update with the filtered options. So that people can link directly to them for others.

The package already updates the url with page numbers (e.g. suffix `?page=2`). Livewire has `$queryString` to facilitate this.

I think this would be a Feature Request though. Updating the `$queryString` may be trivial but getting that to reflect in the query may be more difficult.

**Comment by marksalmon** [comment]
#32
