### ISSUE TITLE
enableSummary() doesn't work

### ISSUE THREAD

**Issue by alexandergziresis** [MedicOneSystems/livewire-datatables#404]
Hi, when i use this function i get this error:

Call to undefined method Mediconesystems\LivewireDatatables\Column::enableSummary()

**Comment by alexandergziresis** [comment]
Excuseme, how i install dev-master in laravel? i only use composer install, thanks for your help

**Comment by thyseus** [comment]
Please see https://github.com/MedicOneSystems/livewire-datatables/issues/403

**Comment by thyseus** [comment]
I was able to publish a `0.7.0` version to packagist.org. Please try this and let me know if it works.

**Comment by alexandergziresis** [comment]
thanks a lot thyseus, i didn't get that error anymore , but nothing happens, by the way the "truncate" function cuts the words but it doesn't show the "tooltip" either

**Comment by thyseus** [comment]
Does the column you want to summary only contain numerical values ?
Please try re-run `npm run dev` to re-bundle all assets.

**Comment by alexandergziresis** [comment]
Yes, it is only numeric values, i run npm run dev but same thing.

**Comment by 3rgo** [comment]
@alexandergziresis Did you publish the assets from a previous release ?
If so, you have to remove them, then re-publish.
It happened to me when I tried it today. I had to review manually all diffs since I did a lot of front-end customizations

**Comment by alexandergziresis** [comment]
Thanks!, the problem was the versión of tailwind, now works!!
