### ISSUE TITLE
How to manage row edit (not inline)

### ISSUE THREAD

**Issue by robman70** [MedicOneSystems/livewire-datatables#475]
Hi,
I'm completely stuck: I'm trying to manage row edit, based on the https://livewire-datatables.com/actions example.
Could someone show me a simple, basic, example of editing a row using a modal form?
An example based on the standard users table would be fine, even if only with the email field.

Thanks a lot

**Comment by hakimj96** [comment]
hi, can you share your ways of solving it? seems I am stuck here as well
