### ISSUE TITLE
Accessors & Mutators

### ISSUE THREAD

**Issue by anishsarkar** [MedicOneSystems/livewire-datatables#48]
Is there a way to use to Accessors & Mutators on a model, without having to write codes?

**Comment by MattHadfield113** [comment]
I would also much prefer this !

**Comment by alshuwaikhat** [comment]
I think one of the issues here is that the package parses its own DB queries; not relying on Eloquent ORM, which is the root cause of this issue. I even had to move from Postgres to MySQL.

**Comment by umarta** [comment]
i also get same problem when migrate to Postgresql

**Comment by Hillnut** [comment]
any news on this feature request? would be so handy to have

**Comment by marksalmon** [comment]
see #48
