### ISSUE TITLE
https://livewire-datatables.com - pagination - All - Doesn't work

### ISSUE THREAD

**Issue by webzaster** [MedicOneSystems/livewire-datatables#50]
The demo site : (https://livewire-datatables.com)
pagination : All 
option doesn't work

**Comment by xitox97** [comment]
work fines for me, just need to wait a bit longer

**Comment by octoquad** [comment]
Definitely a problem. Currently throws a 502 Gateway HTTP error with "Internal server error" JSON response after one second.

**Comment by marksalmon** [comment]
Works for me too. Need more information to reproduce this error

**Comment by octoquad** [comment]
Still a problem:

![image](https://user-images.githubusercontent.com/1165755/98012865-4321f980-1e02-11eb-8895-4db2db46634d.png)

1. Go to https://livewire-datatables.com/simple or https://livewire-datatables.com/complex or https://livewire-datatables.com/actions
1. Click on All on pagination options.
1. Black overlay appears in screenshot above.
