### ISSUE TITLE
HELP - Uncaught (in promise) TypeError: this.messageInTransit is null

### ISSUE THREAD

**Issue by Slobug** [MedicOneSystems/livewire-datatables#504]
Hello

I don't understand this error: Uncaught (in promise) TypeError: this.messageInTransit is null

I see this error only in production unfortunately. and my production is equal to my development except for the content of the tables.

Someone to guide me ?
Thanks

**Comment by thyseus** [comment]
I do not know this error. Please ensure to run `npm run prod` and move that js/css on your production environment.

**Comment by Slobug** [comment]
Laravel  
app\http\livewire\geforia\ChoisesDatatable.php  

in development tool : my_application/livewire/message/geforia.choices-datatable

on mouseover the datatable I have this error : Uncaught (in promise) TypeError: this.messageInTransit is undefined

my_application//vendor/js/component/index.js l.257:64  
`    messageSendFailed() {
        store.callHook('message.failed', this.messageInTransit, this)

        this.messageInTransit.reject()

        this.messageInTransit = null
    }`

**Comment by Slobug** [comment]
the **npm run prod**  has not changed anything

**Comment by Slobug** [comment]
Livewire encountered corrupt data when trying to hydrate the [geforia.choices-datatable] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
