### ISSUE TITLE
Finally, Detailed Report on Column Not Found on Export

### ISSUE THREAD

**Issue by abbasmashaddy72** [MedicOneSystems/livewire-datatables#505]
This Issue Only Occurs when my relation table also has the same column name as that of other related column table

Example:
My Table Patient Has a name field column
&
My Table Locality also Has a name filed column

So at the Time of Export It is Trowing the Error Column not Found

If we fix it Finally, the issue will be solved.

Note:
When I am using same relation with count method in number column, it works fine `users.name:count`
Also, It's working fine with relation if all column names are different.

Please Check This Link: https://flareapp.io/share/LPdda1gP#F70

The Above Link will give more Detailed Report on what we are having the issue on Export
@marksalmon @thyseus @tomshaw @trippo @renardudezert @mrsid18

**Comment by tomshaw** [comment]
Says `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'localities.name' in 'field list'` Try AS localities_name so not to conflict with users.name.

**Comment by abbasmashaddy72** [comment]
`<?php

namespace App\Http\Livewire\Tables;

use App\Models\Patient;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;

class PatientsTable extends LivewireDatatable
{
    public $model = Patient::class;
    public $exportable = true;

    public function builder()
    {
        if (auth()->user()->roles->first()->title == 'Admin') {
            return Patient::query()->with('locality');
        }
        return Patient::query()->with('locality')->where('branch_id', auth()->user()->branch_id);
    }

    public function columns()
    {
        return [
            Column::checkbox()
                ->label('Checkbox'),

            Column::index($this)
                ->unsortable(),

            Column::name('name')
                ->label('Name')
                ->filterable(),

            Column::name('locality.name')
                ->label('Locality Name')
                ->filterable(),

            Column::name('gender')
                ->filterable(['Male', 'FeMale', 'Trans'])
                ->label('Gender'),

            Column::name('blood_group')
                ->filterable(['A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-'])
                ->label('Blood Group'),

            DateColumn::name('dob')
                ->label('Date of Birth')
                ->filterable(),

            Column::name('contact_no')
                ->label('Contact No.')
                ->filterable(),

            Column::name('description')
                ->label('Description')
                ->truncate(40)
                ->filterable(),

            DateColumn::name('created_at')
                ->label('First Visit')
                ->filterable(),

            Column::callback(['id'], function ($id) {
                return view('pages.patient.actions', ['id' => $id]);
            })->excludeFromExport()->unsortable()->label('Action'),
        ];
    }
}`

This is My Code How can I Do it. From My Point of view We Have to change that in export function.

**Comment by abbasmashaddy72** [comment]
> Says `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'localities.name' in 'field list'` Try AS localities_name so not to conflict with users.name.

When Using` ' AS ' `as per user suggestion getting this error
Error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'patients.locality.name' in 'field list'
`
Code:
`Column::name('locality.name as locality_name')`

**Comment by tomshaw** [comment]
@abbasmashaddy72 You may have to build your query with a left join.

**Comment by abbasmashaddy72** [comment]
Okay

It is working fine when I am using join but not when using relationship

**Comment by tomshaw** [comment]
@abbasmashaddy72 Currently working weekdays. Checkout `src/Http/Livewire/LivewireDatatable.php`  specifically methods export() and getExportResultsSet() probably an easy fix.

**Comment by abbasmashaddy72** [comment]
I am on it

**Comment by kirba** [comment]
The issue is not actually with export but with re-render process. When we run export the query will be built twice. The second time it fails because join is not added. It is not added because second time getSelectStatements function is called columns already have `select` prop 

`if ($column->select) {
                    return $column;
                }`
                
Then as a side effect, resolveColumnName doesn't get called and join is not added.

It is easy to test out, if you delete from a view file the entire html where $this->results is mentioned you will have a table with export button only and export will work. Also if you comment out the part of the code that checks if $column already has select prop set, it will again work (this time both render and export)


I had the same issue and did some debugging to come to this. Maybe I could even prepare a PR, but I need more time to figure out if actually the bug is somewhere else, maybe columns should be reset after certain action? @tomshaw let me know if this rings a bell

**Comment by abbasmashaddy72** [comment]
It is correct, the issue is exactly same

did you fund any solution on it
@kirba

**Comment by kirba** [comment]
@abbasmashaddy72 

PR #516 should fix it.

As mentioned in the PR, there is a workaround, you can define join clause in builder function and it will be fine

**Comment by abbasmashaddy72** [comment]
Okay Thanks Bro
