### ISSUE TITLE
New package name ?

### ISSUE THREAD

**Issue by renardudezert** [MedicOneSystems/livewire-datatables#523]
Hi,
I just see in the composer.json file that the package name has been changed. Is there a valid reason ?
It's now `shaneburell/livewire-datatables` instead of `mediconesystems/livewire-datatables`. 
The change was made on the [PR 450](https://github.com/MedicOneSystems/livewire-datatables/pull/450) who was merge on May, 11.
If the fork is the new official package name, i think that it would be great to update the README. Otherwise, don't forget to set the correct name into compose.json file before releasing a new version ;)
Regards

**Comment by thyseus** [comment]
No, i think this was a mistake. Will fix soon. Thanks a lot for reporting 👍

**Comment by thyseus** [comment]
https://github.com/MedicOneSystems/livewire-datatables/commit/0d39c09094fbe18df56265234c38311750fe31c9

**Comment by renardudezert** [comment]
Thanks for your reactivity and the fix ;)
