### ISSUE TITLE
applying filter to a column which is using Eloquent method in itself. 

### ISSUE THREAD

**Issue by rameezmeans** [MedicOneSystems/livewire-datatables#547]
I am trying to filter a column which has a username which I am getting from user_id which here in this context is assigned_id. please help me. 

```
Column::callback('assigned_to', function($id){
                return '<label class="label label-success">'.User::findOrFail($id)->name.'<label>';
            })->label('Assigned to')->filterable(collect(User::findOrFail())->map( function($value, $key) {
                return ['id' => $key, 'name' => $value];
            }))->searchable(),
```

**Comment by mrtorks** [comment]
@rameezmeans From my understanding, a callback would require an attribute that exists on the model class. I see you are using `$id` so I would do this:
```
Column::callback(['id'], function($id){
                return '<label class="label label-success">'.User::findOrFail($id)->name.'<label>';
            })->label('Assigned to')
```
The above should do the trick.
I would have to do some investigation about using filterable because I have never done that. I would have to investigate

**Comment by rameezmeans** [comment]
Thank you for replying. I really appreciate that. Yes, your solution worked fine for the part of the problem. Now I have a dropdown filter with right values but it must filter as well. That dropdown is Not filtering the table. For simplicity, I am using this. 

Column::callback(['assigned_to'], function($id){
                return User::findOrFail($id)->name;
            })->label('Assigned to')->filterable(User::get('name')->pluck('name')->toArray())->searchable(),

**Comment by mrtorks** [comment]
Hi @rameezmeans. A callback using this package needs an array with values you would use in the callback, whether you are doing stuff directly or passing params to a view. 
Your code is not working because the callback is looking for ***`$id`***, which it expects in the array your are passing however you have passed ***`['assigned_to']`*** to the array instead of ***`['id']`***.
I reproduced your question and it worked. using this:
```
Column::callback(['id','name'], function($id){
                return '<label class="label label-success">'.User::findOrFail($id)->name.'<label>';
            })->label('Assigned to')->filterable(User::get('name')->pluck('name')->toArray())->searchable(),
```

I am attaching an image of the code working
<img width="2537" alt="Screen Shot 2023-02-25 at 3 42 38 PM" src="https://user-images.githubusercontent.com/13285039/221379032-10000e41-6ed4-4c2e-a518-8a151aee013c.png">

**Comment by rameezmeans** [comment]
Hi. I really thank you for your effort but it is not working for me. I will try to elaborate. 
1. I have a Files table and I am assigning files to users. 1 to 1 relationship there. File has 'id' and 'assigned_to' is foreign key.  
2. I have to use 'assigned_to' because 'id' will give me ID of file. I can not use that to get Username from User table. 
3. I did use 'id' as you mentioned but unfortunately it is still not working. Here is my query. 

Column::callback(['id','name'], function($id){
                    $assignedTo = File::findOrFail($id)->assigned_to;
                    return User::findOrFail($assignedTo)->name;
                })->label('Assigned to')
                ->filterable(User::get('name')->pluck('name')->toArray())
                ->searchable(),

**Comment by mrtorks** [comment]
Viola!! @rameezmeans I got the select box to use `id` and `name`. We can make solid progress from here. ***Try this***:
```
Column::callback(['id','name'], function($id){
                    $assignedTo = File::findOrFail($id)->assigned_to;
                    return User::findOrFail($assignedTo)->name;
                })->label('Assigned to')
                ->filterable(User::get(['id', 'name']))
                ->searchable(),
```

**Comment by rameezmeans** [comment]
Thank you so much, Sir. The code with the "['id', 'name'] "does provide results but they were Wrong. However, the code with 'assigned_id' worked perfectly as it should be working.

**Comment by mrtorks** [comment]
Glad I was able to help

**Comment by rameezmeans** [comment]
There is only a slight confusion. The Sign which keeps track of Selected items is showing 'id'. It should show 'name'.

**Comment by mrtorks** [comment]
Its a trade of, it would filter by id since id is the value. try it with just `name`. like this:
```
Column::callback(['assigned_to'], function($assigned_to){
                    return User::findOrFail($assigned_to)->name;
                })->label('Assigned to')
                ->filterable(User::get(['id']))
                ->searchable(),
```

**Comment by rameezmeans** [comment]
Yeah. It is a trade off. I am just opening it so that you can keep track of it. I am satisfied. Also I used your code and it broke at this point. 

```
@elseif(is_array($label))
     <option value="{{ $label['id'] }}">{{ $label['name'] }}</option>
@elseif(is_numeric($value))
```

and this was the error. 

"Undefined array key "id"".

**Comment by mrtorks** [comment]
@rameezmeans this is because we do not have id in this collection `User::get(['name'])`. You have to refactor your code to use just `name` in this case.

**Comment by rameezmeans** [comment]
No. That was the code from the file 'resources/views/livewire/datatables/filters/select.blade.php'. It must remain the same otherwise query will bring forward wrong results. 
However, there is a code at the end of same file and this is responsible for printing 'id' instead of name. 

`<span>{{ $this->getDisplayValue($index, $value) }}</span>`

can you tell me where I can find 'getDisplayValue' function?

**Comment by mrtorks** [comment]
Did you publish the package views?

**Comment by rameezmeans** [comment]
Yes. That is why I am getting this code in 'views' folder of My project. I just ddi this at that line and it is wonderful. Thank you for you time and energy. I really appreciate that. 

`<span>{{ \App\Models\User::findOrFail($value)->name }}</span>`

**Comment by mrtorks** [comment]
I updated my response

**Comment by rameezmeans** [comment]
Sorry, but your solution involving line 15 will break everything. There must be 'id' in there. Not 'name'. However, I just updated line 29 of the same file according to my needs. So you may update your response again. It does provide 'name' in display but fetching wrong results. I am use 'id' in 'assigned_to' column. Thanks!

**Comment by mrtorks** [comment]
I would remove that then
