### ISSUE TITLE
Paginatio

### ISSUE THREAD

**Issue by anishsarkar** [MedicOneSystems/livewire-datatables#57]
Pagination to previous page fail. 

To reproduce: the demo site with simaple table. Select a page other than 1, say 5. Once it loads, try the previous page which fails. 

Note the next page link still works. Also, funny thing is than if you reload the page with query string as page=5 (say), then the previous page link works. However, again if you visit a page by clicking on that page, the previous page link stops working.

**Comment by anishsarkar** [comment]
With some more digging, what I can see is that the component is somehow losing the event listener tagged with the previous page link. If one opens the network tab, keeps a watch on the link of previous page, it looks like the event listener is not registering when from page 1 one moves to page 4 (say). If you reload the page with query string 

page=4

the event listener of the previous page link is back and it seems to work. The same behaviour is seen with the last page if you reload the page when you are on the last page. Again if you move click on some page, the event listener does not seem to register.

**Comment by agustind** [comment]
Same problem for me, did you find a solution?

**Comment by anishsarkar** [comment]
Yes, indeed. The problem seems to be  that livewire is not detecting the pagination button as a new one (not present in the original dom) and hence not attaching the event listeners. So, I put IDs to all the buttons - like : pagination-mobile-prev, pagination-mobile-next, pagination-desktop-prev, pagination-desktop-prev-disabled, pagination-desktop-page-{{ $page }} and so on. This seems to work fine.

I had actually rewritten the blade file for pagination, I used cool-gray shades for the pages, so I used cool-gray for pagination buttons also. Also another thing that I don't like about this pagination is that when there is a single page of results, the result summary is not shown. Unfortunately I am in quarantine and unable to go to office and I can't share the updated blade file. Once I am out of quarantine, I will post the blade file.

**Comment by agustind** [comment]
Maybe you are referring to this problem I also had: let's say you have 10 pages, you click on page 5, then you search, the search returns only one page of results but you are still on page 5 so you don't see anything. Livewire datatables should take you to page 1 after searching, I've fixed this by editing the blade file, adding some javascript that triggers a click on the page 1 link.

```

<script>

$(document).ready(function() {

      $('button[wire\\:click="gotoPage(1)"]').trigger('click');

});

</script>


```

Here's my /resources/views/livewire/datatable.blade.php which fixes this issue:

[datatable.blade.php.zip](https://github.com/MedicOneSystems/livewire-datatables/files/5533560/datatable.blade.php.zip)

**Comment by anishsarkar** [comment]
I am NOT using jquery. Have a default laravel 8 app (not being able to work on that due to quarantine) which uses essentially tall stack. So I am using basic livewire call. In fact, that works very well if you add some IDs to the buttons in the pagination blade. Hopefully in a week, I will be out of quarantine and be able to share the blade file.

**Comment by anishsarkar** [comment]
> Maybe you are referring to this problem I also had: let's say you have 10 pages, you click on page 5, then you search, the search returns only one page of results but you are still on page 5 so you don't see anything. Livewire datatables should take you to page 1 after searching, I've fixed this by editing the blade file, adding some javascript that triggers a click on the page 1 link.
> 
> ```
> 
> <script>
> 
> $(document).ready(function() {
> 
>       $('button[wire\\:click="gotoPage(1)"]').trigger('click');
> 
> });
> 
> </script>
> ```
> 
> Here's my /resources/views/livewire/datatable.blade.php which fixes this issue:
> 
> [datatable.blade.php.zip](https://github.com/MedicOneSystems/livewire-datatables/files/5533560/datatable.blade.php.zip)

Sorry misunderstood your problem. The livewire way to fix it will be to add a public method updatedSearch. Something like 


public function updatedSearch()
 {

$this->page = 1; 
}

That should do it. I am doing it from my phone only, cannot format it correctly.

 In fact I think there is a method called resetPage in the trait, which does the same thing.

**Comment by anishsarkar** [comment]
> Yes, indeed. The problem seems to be that livewire is not detecting the pagination button as a new one (not present in the original dom) and hence not attaching the event listeners. So, I put IDs to all the buttons - like : pagination-mobile-prev, pagination-mobile-next, pagination-desktop-prev, pagination-desktop-prev-disabled, pagination-desktop-page-{{ $page }} and so on. This seems to work fine.
> 
> I had actually rewritten the blade file for pagination, I used cool-gray shades for the pages, so I used cool-gray for pagination buttons also. Also another thing that I don't like about this pagination is that when there is a single page of results, the result summary is not shown. Unfortunately I am in quarantine and unable to go to office and I can't share the updated blade file. Once I am out of quarantine, I will post the blade file.

Here is the blade file that I had created for the purpose. Seems to work flawlessly so far. Hope it will help you.


[pagination.blade.zip](https://github.com/MedicOneSystems/livewire-datatables/files/5720647/pagination.blade.zip)
