### ISSUE TITLE
attributes/appends

### ISSUE THREAD

**Issue by rodrigocardenas** [MedicOneSystems/livewire-datatables#58]
Hi, 
any way how to use attributes/appends from models?
btw nice work thx!

**Comment by vandadsoft** [comment]
Any Solution?

**Comment by carlituxman** [comment]
I've do this:

```
Column::callback(['id'], function ($id) {
                return MyModel::find($id)->my_attribute;
            })->label(__('MyName')),
```

**Comment by amaurycid** [comment]
For now, you should define accesors through callbacks. This package use fluent queries in its inner workings, not Eloquent (that's why model accessors doesn't work).

**Comment by mahmod2000** [comment]
Hi
@carlituxman s solution is not good for huge data in table.

@marksalmon do you have another solution or trick about that ?

**Comment by marksalmon** [comment]
Livewire Datatables uses query builder and SQL directly because hydrating eloquent models is not permormant with large datasets. Therefore you do have to redefine your accessors either in an SQL query using ```Column::raw()``` or in a callback method.

**Comment by shahidkarimi** [comment]
@marksalmon the callback should have access to the current row. like

```
Column::callback(function($row){
  return $row->custom_attribute;
})
```
What's wrong implemting this?
