### ISSUE TITLE
compatible laravel 10

### ISSUE THREAD

**Issue by marco121942** [MedicOneSystems/livewire-datatables#588]
I am trying to use the package for my project in laravel 10
  "php": "^8.1",
         "guzzlehttp/guzzle": "^7.2",
         "laravel/framework": "^10.10",
         "laravel/sanctum": "^3.2",
         "laravel/tinker": "^2.8",
         "livewire/livewire": "^2.12"

Please, I would like to know when it will be available so that it is compatible with Laravel 10, please.

**Comment by Nowocyn** [comment]
With the latest release it is now supporting laravel 10 but not livewire v3 yet.

This issue can be closed.
