### ISSUE TITLE
How do I customize the dropdown of records per page?

### ISSUE THREAD

**Issue by jprograming** [MedicOneSystems/livewire-datatables#60]

**Comment by miten5** [comment]
add `per-page="20"` to your livewire component

eg:
```
<livewire:datatable
    model="App\User"
   per-page="20"
/>
```

**Comment by jprograming** [comment]
I mean the list of items from the drop down menu.

**Comment by MillerAdulu** [comment]
To be able to customize this, publish the views from the package by  using:
`$ php artisan vendor:publish` the choose the `Provider: Mediconesystems\LivewireDatatables\LivewireDatatablesServiceProvider` option

After, open `views.livewire.datatables.datatable` and on lines `150-158` you have the drop down menu that you can be able to customize to your liking.
