### ISSUE TITLE
Question: Reload component with new parameter

### ISSUE THREAD

**Issue by reefebba** [MedicOneSystems/livewire-datatables#63]
I have someething like this:

```public function builder()
    {
        return DailyRecord::query()->where('parameter_id', $this->parameter)->whereBetween('datetime', [Carbon::parse($this->from)->format('Y-m-d H:i:s'), Carbon::parse($this->to)->format('Y-m-d H:i:s')]);
    }
```

where I mounted those parameters from parent component, and it works
I need to put the filter outside data table hence I can't use provided filter feature 

from the parent component I tried emitting ```refreshLivewireDatatable``` event hoping it would refresh the datatable with new parameter but it doesn't, it just refreshed the datatable

any way I could do this ?

**Comment by ctschetter** [comment]
Have the same issue. How can the datatable see a parameter update?

**Comment by amosgamaliel** [comment]
any update on this issue?
