### ISSUE TITLE
Filters from external form

### ISSUE THREAD

**Issue by jprograming** [MedicOneSystems/livewire-datatables#68]
Hi,
I have an external filter form and I require that when pressing a button, the filters are applied on the query and the data table is refreshed.

Thanks.

**Comment by carlituxman** [comment]
I do and works:

on external livewire component:
```
public function filter($f)
{
    $this->emit('dttFilter', $f);
}
```

and in LivewireDatatable component:
`protected $listeners = [ 'dttFilter' ];`

and:
```
public function dttFilter($f)
{
    $this->clearFilters();
    $this->doSelectFilter(5,$f);
}

```

**where 5 is the index column**

**Comment by carlituxman** [comment]
another solution:
`public $beforeTableSlot = 'components.app-filters'; `

and in components/app-filters.blade.php has the buttons filter:
`<button wire:click="dttFilter(5, {{$id}})">button</button>`

**where $id param is the desired value filter**
