### ISSUE TITLE
Filtering on Sqlite fails

### ISSUE THREAD

**Issue by waffshappen** [MedicOneSystems/livewire-datatables#70]
Sqlite does not support the "separator" argument in
https://github.com/MedicOneSystems/livewire-datatables/blob/9645df8f6c9140624a0ec36d0621b033bd76e12c/src/LivewireDatatablesServiceProvider.php#L143

And neither can it directly support distinct column , 'separator':
https://stackoverflow.com/questions/13382856/sqlite3-join-group-concat-using-distinct-with-custom-separator#13384522

But replacing it with a noop
```php
new Expression($aggregate."(REPLACE(DISTINCT({$column}), '', '') , ', ')")
```
seems to work (but there's not guarantee that it will be actually distinct if the SO comments are any indicators)

**Comment by marksalmon** [comment]
I'm afraid I don't know enough to be able to support sqlite
