### ISSUE TITLE
Separating display string from cell html?  Thoughts?

### ISSUE THREAD

**Issue by jjrohrer** [MedicOneSystems/livewire-datatables#73]
Firstly - I love this library - thanks for making it! (and I'm super impressive with all of the livewire and sql slinging happing here)

I've run in to a couple of problems worth discussing. The first happened when I tried format an email into a `<a href="mailto:email">email</a>` block.  It looked great, but when I searched on an email, things got wacked.

You can see this  https://livewire-datatables.com/complex when you search on, say 'heath' which is in an email. Instead of highlighting the 'heath' in `heathcote.dorothy@example.org` we see `<span class="bg-yellow-100">heath</span>cote.dorothy@example.org`. And the underlying href is messed up, too.
`<a href="mailto:<span class=&quot;bg-yellow-100&quot;>heath</span>cote.dorothy@example.org" class="hover:text-blue-600">&lt;span class="bg-yellow-100"&gt;heath&lt;/span&gt;cote.dorothy@example.org</a>`

The href gets messed up because the 'highlight' function does a simple replace on the value, destroying its usefulness as the original column value to anyone down the line, like the views. In other words, the view gets the pre-highlighted value.

Anyway- I ignored this and tried making a table of users, where clicking the user's name would pop up a dialog showing user details, and an ability to edit them. This started to work for me, but the table started behaving badly. 

Basically, I think some problems might go away if we could add a `->renderCell($columns, $closure)` method that got called just before rendering in the blade. Something like this...

```
 class UsersTable extends LivewireDatatable
{
    public $model = \App\Models\User::class;
    public function columns()
    {
        return [
             Column::name('name')
                ->label('Person')
                ->render(['id','email_verified_at'], function($value, $prettyValue, $id, $email_verified_at) {
                    $trustLevel = ($email_verified_at) ? 'trusted' : 'untrusted';
                    return "<div class='text-3xl' alt='Hint: $value is a $trustLevel person.'>$prettyValue</div>";
                    // This shows the person's name, maybe partially highlighted.
                    // If you hovered over the name, the hint would indicate whether their email had been verified.
                })
                ,
             Column::name('email')
                ->label('E-Mail')
                ->render(['id','name',], function($value, $prettyValue, $id, $name, $email) {
                    return "<a href='mailto:$value'>$prettyValue</a>";
                    // Note: $prettyValue might include html highlighting, but $value would remain useful
                })
                ,
```

I tried developing my own solution, but when I got in to the datatable blade, and got to `$result->{$column['name']}`. I was going to add a renderCell method to the Column class, but this column is not the original column object I was hoping to see.

So, basically, I want to a cleaner way to render html and alpine/ajax/livewire in a cell. I'm happy to help make this happen, or learn how to do it within the existing framework.

Thoughts?  Is anyone else encountering this? How are you dealing with it.

**Comment by jjrohrer** [comment]
Just to follow up... I know some of the above ideas won't work as proposed, or they might not coincide with the architectural style of livewiredatables, but I'm trying to figure out what a working solution would actually look it.

**Comment by jjrohrer** [comment]
After some thought, I don't think $prettyValue should exist. Basically, if the 'render' closure is to be called, then highlighting should not be automatically applied. The closure could call the highlight method itself, if desired.

**Comment by jihadismail8** [comment]
am facing the same issue , i am trying to put some html in the label , but it does not render , it just outputs it as a string . any idea on how for example to add a <span title="sometext">LABEL </span>   ?
