### ISSUE TITLE
Feature Request: set default values to filters

### ISSUE THREAD

**Issue by paulmod** [MedicOneSystems/livewire-datatables#78]
is it possible to add a method that set a default value to a filter?
`Column::name('name')->filterable()->filterDefault('John')`
`DateColumn::name('date')->filterable()->filterDefault(['start' => '1970-01-01', 'end' => '1970-12-31')`

**Comment by amit-viacon** [comment]
$this->activeSelectFilters[9][0] = true;

**Comment by gotroch** [comment]
> You can do this Inside builder method:
> 
> ```
> $this->activeSelectFilters[9][0] = "Default value";
> ```
> 
> *Replace "9" with the appropriate column number

The results are then properly filtered by the new defaults but those default settings are not displayed in the header row. I tried to call $this->refreshLivewireDatatable() with no luck.

**Comment by plassani** [comment]
I did it with redefining mount() function.

Something like:
```
    public function mount(
        $model = null,
        $include = [],
        $exclude = [],
        $hide = [],
        $dates = [],
        $times = [],
        $searchable = [],
        $sort = null,
        $hideHeader = null,
        $hidePagination = null,
        $perPage = 10,
        $exportable = false,
        $hideable = false,
        $beforeTableSlot = false,
        $afterTableSlot = false,
        $params = []
    )
    {
        parent::mount($model,
            $include,
            $exclude,
            $hide,
            $dates,
            $times,
            $searchable,
            $sort,
            $hideHeader,
            $hidePagination,
            $perPage,
            $exportable,
            $hideable,
            $beforeTableSlot,
            $afterTableSlot,
            $params);
        $this->activeBooleanFilters[4] = "1";
    }

```

**Comment by goldjunge4** [comment]
> > You can do this Inside builder method:
> > ```
> > $this->activeSelectFilters[9][0] = "Default value";
> > ```
> > 
> > 
> > *Replace "9" with the appropriate column number
> 
> The results are then properly filtered by the new defaults but those default settings are not displayed in the header row. I tried to call $this->refreshLivewireDatatable() with no luck.

I have the same issue, no filter set visible and I also get an error when selecting others and deselecting the default one.

**Comment by amit-viacon** [comment]
You can also set the appropriate property inside your table class. For example:

```php

public $activeBooleanFilters = [
    3 => 1,
    4 => 0
];

public activeSelectFilters = [
    9 => ["Default value"]
];

```

**Comment by amaurycid** [comment]
Set you defaults on mount():

public $activeBooleanFilters = [];

public $mount()
{
    $this->activeBooleanFilters[4] = "1";
}


Then wire:model the control to the activeFilter you had setted the defaults to:

<input wire:model="activeBooleanFilters[4]" />

**Comment by jjmpsp** [comment]
+1 This would be a really nice addition.

**Comment by trippo** [comment]
+1

**Comment by abbasmashaddy72** [comment]
> 

How to use this please give a demo code on builder thanks

@amit-viacon

**Comment by Cosnavel** [comment]
Hey guys. I have added this Feature. Would love to have your feedback on it. 

Refs #527
