### ISSUE TITLE
Database prefix error

### ISSUE THREAD

**Issue by serwin35** [MedicOneSystems/livewire-datatables#80]
Hi, 

I created a php file that contains a link to the model, I created the columns I want to use and added the ability to search by columns. After entering the searched phrase in the column, I get the error as below. How can I fix the script to take into account the database prefix? Because he evidently missed it?

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'documents_commercials.number' in 'where clause' (SQL: select count(*) as aggregate from 'fs_documents_commercials' where (((LOWER(documents_commercials.number) like %pa%)))) (View: /var/www/html/resources/views/livewire/datatables/datatable.blade.php)`

-= EDIT =-

I have located the problem, it is about the following function, more precisely `return "COALESCE($select, '')";` is missing the table prefix

`public function resolveAdditionalSelects($column)
    {
        $selects = collect($column->additionalSelects)->map(function ($select) {
            return Str::contains($select, '.')
                ? $this->resolveRelationColumn($select, Str::contains($select, ':') ? Str::before($select, ':') : null)
                : $this->query->getModel()->getTable().'.'.$select;
        });
        return $selects->count() > 1
            ? new Expression('CONCAT_WS("'.static::SEPARATOR.'" ,'.
                collect($selects)->map(function ($select) {
                    return "COALESCE($select, '')";
                })->join(', ').')')
            : $selects->first();
    }`

**Comment by bagusindrayana** [comment]
i have same problem here,i think this because use some raw function like `orWhereRaw`,default laravel always add prefix on all query except raw query,i currently just add manually prefix to some raw function like `$query->orWhereRaw('LOWER(tb_'.$col.') like ?', "%$search%");`

**Comment by viableart** [comment]
> Hi,
> 
> I created a php file that contains a link to the model, I created the columns I want to use and added the ability to search by columns. After entering the searched phrase in the column, I get the error as below. How can I fix the script to take into account the database prefix? Because he evidently missed it?
> 
> `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'documents_commercials.number' in 'where clause' (SQL: select count(*) as aggregate from 'fs_documents_commercials' where (((LOWER(documents_commercials.number) like %pa%)))) (View: /var/www/html/resources/views/livewire/datatables/datatable.blade.php)`
> 
> -= EDIT =-
> 
> I have located the problem, it is about the following function, more precisely `return "COALESCE($select, '')";` is missing the table prefix
> 
> `public function resolveAdditionalSelects($column) { $selects = collect($column->additionalSelects)->map(function ($select) { return Str::contains($select, '.') ? $this->resolveRelationColumn($select, Str::contains($select, ':') ? Str::before($select, ':') : null) : $this->query->getModel()->getTable().'.'.$select; }); return $selects->count() > 1 ? new Expression('CONCAT_WS("'.static::SEPARATOR.'" ,'. collect($selects)->map(function ($select) { return "COALESCE($select, '')"; })->join(', ').')') : $selects->first(); }`

Looks like they're not using the DB-> prefix when searching. 
If you want to use it with prefix, you can change the follow file:
vendor/mediconesystems/livewire-datatables/src/Http/Livewire/LivewireDatatable.php

`line: 718, $query->orWhereRaw('LOWER(prefix_'.$col.') like ?', "%$search%");`
`line: 721, $query->orWhereRaw('LOWER(prefix_'.$column.') like ?', "%$search%");`

**Comment by lakshmi10113** [comment]
Is it possible to get a pull request for this?

**Comment by robinflyhigh** [comment]
@viableart @lakshmi10113 Checkout https://github.com/MedicOneSystems/livewire-datatables/pull/298

**Comment by zachary** [comment]
yes, same issue as above

**Comment by serwin35** [comment]
Thx
