### ISSUE TITLE
BooleanColumn::callback wasn't working correctly

### ISSUE THREAD

**Issue by ZerglingGo** [MedicOneSystems/livewire-datatables#82]
I encountered the following problem when using BooleanColumn::callback

Codes to reproducing problems:
```php
// Icon prints correctly when without using callback
BooleanColumn::name('email_verified_at')

// Icon wasn't printing when using callback
BooleanColumn::callback('email_verified_at', function ($emailVerifiedAt) {
    return $emailVerifiedAt != NULL;
})
```
Two columns printing like below image
![image](https://user-images.githubusercontent.com/3365053/99300541-1a811180-2890-11eb-954e-8237f7a14490.png)

**Comment by LuanHimmlisch** [comment]
@marksalmon has this been fixed? Because I'm facing the same issue
