### ISSUE TITLE
how to show image 

### ISSUE THREAD

**Issue by begeng11** [MedicOneSystems/livewire-datatables#86]
sorry maybe out of topic .. 
im trying to show image on datatable but 

i use varchar to save image in database
this is my code :

`Column::name('image', function ($simage) {
  $url =asset('storage/images/banner/'.$simage->image);
  return '<img src='.$url.' border="0" width="40" class="img-rounded" align="center" />';
   }),`

the output is image name not the image
can somebody help ?

**Comment by crThiago** [comment]
Try using callback method

```
Column::callback(['image'], function ($image) {
    $url = URL::asset('storage/images/banner/' . $image);
    return '<img src="$url">';
})
```

**Comment by begeng11** [comment]
> Try using callback method
> 
> ```
> Column::callback(['image'], function ($image) {
>     $url = URL::asset('storage/images/banner/' . $image);
>     return '<img src="$url">';
> })
> ```

hey thank you now its work .. 
this my final code 

```
Column::callback(['image'], function ($image) {
                $url = ('storage/images/banner/' . $image);
                return '<img src='.$url.' >'; 
```
