### ISSUE TITLE
Select and Filter not working correctly

### ISSUE THREAD

**Issue by MattHadfield113** [MedicOneSystems/livewire-datatables#88]
Hello,

Firstly, great package, this is going to save me a ton of time in building our new systems.

Secondly, i have noticed an oddity.

Whenever i add a text filter, it adds it into column 0 instead of the relevant column, not sure why this is ?

**Steps to replicate -**

1.  No Filters Set

![image](https://user-images.githubusercontent.com/30897252/100242773-16f32780-2f2d-11eb-818d-33a19fa16ed4.png)

2. Enter a text filter, in this case in the brand field.

![image](https://user-images.githubusercontent.com/30897252/100242945-443fd580-2f2d-11eb-8def-f739e4848efc.png)

3. Filter then applies, but is moved over to the "name" column instead.

![image](https://user-images.githubusercontent.com/30897252/100243052-6174a400-2f2d-11eb-991e-d500857ee1c1.png)

**Comment by pvanhemmen** [comment]
I can confirm this issue, which was introduces with livewire 2.3.2. A downgrade to livewire 2.3.1. fixes the bug for now.
