### ISSUE TITLE
Row Filter breaks with Livewire 2.3.2

### ISSUE THREAD

**Issue by waffshappen** [MedicOneSystems/livewire-datatables#89]
Attempting to filter rows on 2.3.2 results in no output on tables.

This works if enforcing 2.3.1 via composer.json

Probably related to 
https://github.com/MedicOneSystems/livewire-datatables/issues/88

**Comment by ValulifeAndy** [comment]
activeSelectFilters.
I have downgraded as suggested but it is still not working.

if I hardcode the variable 
public $activeSelectFilters = [4=>['In Progress']];
Into the Class it works and filters the records correclty.

**Comment by santhika29** [comment]
@waffshappen it's working on livewire 2.3.3
