### ISSUE TITLE
Modals for actions (create, edit, delete)

### ISSUE THREAD

**Issue by marioene** [MedicOneSystems/livewire-datatables#90]
Hi! First, great package!

I want to implement Bootstrap 4 modal on different actions (edit or delete) in my LivewireDatatable component, but I am stuck right now.

1. How can I call an edit form in a modal with values from every row? Can I use wire:model in my modal form?

2. Where can I validate and save the values resulted from the update action from the form?

3. It is possible to show me a small example?

**Comment by santhika29** [comment]
1. yes u can call it just using the id
2. u can use another package form
3.
 `<button wire:click="$emit('tindakanEdit',{{ $id }})" class="p-1 text-blue-600 hover:bg-blue-600 hover:text-white rounded">
        <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg>
    </button>`
that's my code to call the modal

**Comment by marioene** [comment]
> 
> 
>     1. yes u can call it just using the id
> 
>     2. u can use another package form
> 
> 
> `<button wire:click="$emit('tindakanEdit',{{ $id }})" class="p-1 text-blue-600 hover:bg-blue-600 hover:text-white rounded"> <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg> </button>`
> that's my code to call the modal

But in tindakanEdit method you will open the modal form. It was a good example to show all the methods. Thanks.

**Comment by santhika29** [comment]
here is my modal form:
in edit.blade.php
```
<div class="fixed inset-0 z-10 overflow-y-auto ease-out duration-400" >
    <div class="flex items-end justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 transition-opacity">
            <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
        </div>
        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>​
        <div class="absolute top-0 right-0 z-50 flex flex-col items-center mt-4 mr-4 text-sm text-white cursor-pointer modal-close" wire:click="closeModal()">
            <svg class="text-white fill-current" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
              <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
            </svg>
            <span class="text-sm">(Esc)</span>
          </div>
        <div class="inline-block overflow-visible text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl sm:my-8 sm:align-middle sm:max-w-xl md:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">
            <div class="px-4 py-4" >
                 <!-- load your form here -->
            </div>
        </div>
    </div>
</div>
<script>
    document.onkeydown = function(evt) {
      evt = evt || window.event
      var isEscape = false
      if ("key" in evt) {
    	isEscape = (evt.key === "Escape" || evt.key === "Esc")
      } else {
    	isEscape = (evt.keyCode === 27)
      }
      if (isEscape) {
    	livewire.emit('closeModalx')
    	//livewire.emit('resetFormData')
      }
    };

</script>
```
