### ISSUE TITLE
Exported columns with callbacks header names are incorrect

### ISSUE THREAD

**Issue by eddyinet** [MedicOneSystems/livewire-datatables#93]
Simply awesome package. 

Minor issue with exporting columns that are callbacks. The column headers show something like : "callback_2323557737" instead of the column name. For example if you export the complex demo table (https://livewire-datatables.com/complex) the computedBedtime column shows up as "callback_2323557737".

**Comment by bird-c** [comment]
i used this to solved the header name it will output NAME on the header,

`Column::raw("CONCAT(p.first_name,' ',p.middle_name,' ',p.last_name) AS NAME")
  ->label('NAME'),`

**Comment by eddyinet** [comment]
> i used this to solved the header name it will output NAME on the header,
> 
> `Column::raw("CONCAT(p.first_name,' ',p.middle_name,' ',p.last_name) AS NAME") ->label('NAME'),`

Appreciate the response! The "label" property works great for the HTML column headers but the exported headers don't take it into account and still have the callback_ reference instead.

**Comment by amaurycid** [comment]
I sorted out with these:

// On livewire datatatble class

public function getReports()
{
	// skipped columns with no label or hidden
	$columns = collect($this->columns)->reject(function ($value, $key) {
	    return $value['label'] == null || $value['hidden'] == true;
	});

	// build array of column names
	$column_names = $columns->map(function ($value, $key) {
	    return $value['name'];
	})->all();

	$mapped = $this->mappedCallbacks(
	    $this->getQuery()->get()
	);

	// filter column name data results
	$results = $mapped->map(function ($item, $key) use ($column_names) {
	    return collect($item)->only($column_names)->all();
	});

	$data['columns'] = $columns;
	$data['results'] = $results;

	return $data;
}
    

public function excelExport()
{
	$this->forgetComputed();

	return Excel::download(new ExcelReportController($this->getReports()), 'Consumer-shift-export.xlsx');
}


// On ExcelExport class 
   
public function headings(): array
{
	$columns = $this->report['columns'];

	$headings = $columns->map(function ($value, $key) {
	    return $value['label'];
	})->all();

	return $headings;
}

Hope it helps.

**Comment by eddyinet** [comment]
@amaurycid Thank you! This looks great... So are you just calling excelExport on your own bypassing the built in Export button?

**Comment by eddyinet** [comment]
@amaurycid What did you use for the Use path for ExcelReportController?

**Comment by amaurycid** [comment]
eddyinet

<pre>
<?php

namespace App\Http\Controllers;

use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;

class ExcelReportController implements FromCollection, WithHeadings
{
    use Exportable;

    public $report;

    public function __construct($report)
    {
        $this->report = $report;
    }

    public function collection()
    {
        return $this->report['results'];
    }

    public function headings(): array
    {
        $columns = $this->report['columns'];

        $headings = $columns->map(function ($value, $key) {
            return $value['label'];
        })->all();

        return $headings;
    }
}
</pre>

**Comment by eddyinet** [comment]
@amaurycid Beautiful! Thank you sir! 

For anyone who comes across this I had to 

1) Tweak Livewire.Datatable.php -> mapCallbacks in the vendor directory to use $paginatedCollection->collect() instead of $paginatedCollection->getCollection()

2) Change the getReports function to use 

$mapped = $this->mapCallbacks(
            $this->getQuery()->get()
        );

3) Bonus: Rename excelExport() to just export() to override the built in export button call.

Now I just need to figure out how to get the columns not to use the callback return values but it should be easy based on this code. I'll try and update once I resolved. Thank you again @amaurycid !!!

**Comment by amaurycid** [comment]
@eddyinet 
On you point #1 
I would suggest not to touch vendor directory files. That's because on updates, that changes might be gone.
Just override methods on you new component controllers, as I did on the examples.

**Comment by eddyinet** [comment]
@amaurycid 100% spot on. I just wanted to mention it in case it takes me a while to work up the courage to put together my first PR ;-) Overriding the method until then works perfect. Thank you again!

**Comment by IlhamriSKY** [comment]
> $this->exportcolumns

I have problem like this
`Property [$exportcolumns] not found on component:`

I already declare exportcolumns at getReports function

```
public function getReports()
{
  // skipped columns with no label or hidden
  $this->exportcolumns = true;
  $columns = collect($this->columns)->reject(function ($value, $key) {
      return $value['label'] == null || $value['hidden'] == true;
  });
}
```

**Comment by IlhamriSKY** [comment]
> @amaurycid Beautiful! Thank you sir!
> 
> For anyone who comes across this I had to
> 
> 1. Override Livewire.Datatable.php -> mapCallbacks method to use $paginatedCollection->collect() instead of $paginatedCollection->getCollection()
> 2. Change the getReports function to use
> 
> ```
> $mapped = $this->mapCallbacks(
>             $this->getQuery()->get()
>         );
> ```
> 
> 1. Bonus: Rename excelExport() to just export() to override the built in export button call.
> 
> Now I just need to figure out how to get the columns not to use the callback return values but it should be easy based on this code. I'll try and update once I resolved. Thank you again @amaurycid !!!
> 
> Edits:
> 
> Updated 1 as per override suggestion by amaurycid. Thank you!
> 
> Dirty hack if you have callback columns that have extra formatting for example which aren't appropriate for export is to set a variable in getReport prior to collecting columns and return appropriately in columns call:
> 
> // columns method
> 
> ```
> NumberColumn::callback(['orders.orderid'], function ($id){
>                 if($this->exportcolumns){
>                     return $id;
>                 }else{
>                     return '<a href="/order/'.$id.'">'.$id.'</a>';   
>                 }  
>             })->label('Order ID')->searchable()
> ```
> 
> // From getReports
> 
> ```
>         $this->exportcolumns = true;
>         $columns = collect($this->columns)->reject(function ($value, $key) {
>             return $value['label'] == null || $value['hidden'] == true;
>         });
> ```

I have applied all the solutions above, but when I want the costume display to return from the callback, when the table does not appear the costume display

This is my callback
`			Column::callback(['users.username', 'userid'], function ($username, $userid) {
				if($this->columns){
					$return = $username;
				}else{
					$return = "<a href='" . route('users.show', ['user' => $userid]) . "'>$username</a>";
				};
				return $return;
			})->label('Username'),`
			

In the table and excel that I downloaded, only the results show **$username**

**Comment by vipertecpro** [comment]
Please resolve this

**Comment by vipertecpro** [comment]
Perfect this is great, it's working fine. Thank you so much my lord, I shall continue contributing to this from now on.
