### ISSUE TITLE
Remember settings of the tables

### ISSUE THREAD

**Issue by WimDeMeester** [MedicOneSystems/livewire-datatables#95]
Is there a way to remember the settings of the tables?  I mean, if a user has hidden some columns or sorted on a certain column, how can the user return to the same page later, with the same filter options, the same hidden columns, ...

If this is not possible, can someone give me some hints on how to do this?  Using sessions or putting everything in the database?

**Comment by WimDeMeester** [comment]
If I find the time, I might try to make a PR for this, but I need some instructions on how I should implement this.  Putting the information in the database or using sessions...

**Comment by emageint** [comment]
I have the same issue and I would use sessions

**Comment by hakman-dev** [comment]
Would also love this

**Comment by pitr82** [comment]
Yes it will be great feature

**Comment by pitr82** [comment]
Is there any progress with save setting to session ?

**Comment by tkerns** [comment]
I am also hoping for this feature.

**Comment by MACscr** [comment]
I am really needing this as well. Super simple to do with jquery datatables.

**Comment by thyseus** [comment]
Are there any updates about this feature request ? I would like to implement this feature, but i am unsure about what would be the correct approach. The simplest way imho is to provide a single JSON column in any table, bound to an user_id.

**Comment by WimDeMeester** [comment]
I didn't have the time to implement this, and I don't have time in the foreseeable future to work on it.  So, please go ahead!  I don't have a strong opinion on how this could be implemented.

**Comment by WimDeMeester** [comment]
Can this be closed now that #274 is merged and released?

**Comment by thyseus** [comment]
As far as everyone is pleased with the implementation, yes.
