### ISSUE TITLE
Searching does not match searchable values when using pagination or moving through pages.

### ISSUE THREAD

**Issue by xrezut** [MedicOneSystems/livewire-datatables#96]
There is an issue with searching when using the pagination.

The searching works on the first page. However, when searching for the same value after moving between pages no matches are found. 

Image below shows the "abe lynch" matching when searching from the first page.
![image](https://user-images.githubusercontent.com/31830718/101664574-ec808e80-3a43-11eb-8d81-4a4114695d64.png)

However, the same search query as shown below does not match due to moving to another page.
![image](https://user-images.githubusercontent.com/31830718/101664847-39fcfb80-3a44-11eb-9dfd-0568036c18f0.png)

To reproduce follow these steps (can be reproduced with the intermediate example of the demo app as well):

- [ ] Search for any searchable value whilst on page 1. (Should filter the results)

- [ ]  Switch to another page using the pagination buttons

- [ ] Search the same query again (Search fails)

**Comment by davidjr82** [comment]
There is a workaround in #39

**Comment by xrezut** [comment]
> 
> 
> There is a workaround in #39

Thank you very much. I can confirm this does work to fix the issue.
