### ISSUE TITLE
php 8 support

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [MedicOneSystems/livewire-datatables#97]

**Comment by evici** [comment]
cmon dude :) there are 2 PRs for this already.

**Comment by ahmedsayedabdelsalam** [comment]
great 👌 there were not when I submitted this :D

**Comment by evici** [comment]
> great 👌 there were not when I submitted this :D

This was ment to creator. The issue still not resolved.. sadly. But you can involve —ignore-platform option when pulling it with composer

**Comment by MattHadfield113** [comment]
Another vote for PHP 8 Support

**Comment by rickmills** [comment]
So the php8 pr was merged, but theres no tagged release with php8 support. Until it gets tagged you're forced to use `dev-master`.

**Comment by mattmarkwick** [comment]
Bump on this - can we have a new release tagged with the now merged php 8 support included please? Don't want to be messing around with dev branches or ignoring requirements for a production build. Currently our only option is to downgrade prod php version.
